### ISSUE TITLE
Allow Argument default to be value 'omitted'

### ISSUE THREAD

**Issue by cefn** [pallets/click#1030]
I have click decorators like this 

```python
@click.command()
@click.argument("target", type=click.Choice(brains), default="vanguard")
```

I would rather be able to tell if an argument has been specified (allowing me to use 'pythonic' strategies for defaults) but the following two approaches are invalid for different reasons.

1) This is invalid because None is not drawn from the 'brains' list of valid strings

```python
@click.command()
@click.argument("target", type=click.Choice(brains), default=None)
```

2) Adding it as a value is invalid because None is not a string

```python
@click.command()
@click.argument("target", type=click.Choice(brains + [None]), default=None)
```

The only thing which seems to work is this...

3) Use empty string and add it to the choices list

```python
@click.command()
@click.argument("target", type=click.Choice(brains + [""]), default="")
```

I'm really hoping for something a big less hacky and error-prone. Relaxing any of the constraints which limited the other options would make it somewhat better e.g.

Allow a default to not be in the list
Allow a list entry to not be a string 

However, ideally, an argument would also have potential to be optional (no value being passed to the decorated function if not found in the command line), as per https://github.com/pallets/click/issues/1029 which would look like

```python
@click.command()
@click.argument("target", type=click.Choice(brains), optional=True)
```

**Comment by jcrotts** [comment]
I think Arguments by design are not suppose to have these sorts of flags. According to the docs, they are simple by design because of their limited syntax.

You can always pass in a subclass of Argument that has the special validation you want. Alternatively you can also put a callback in argument that would do type validation for you.

Let me know if you have questions about those approaches or they don't work for your use case.
