### ISSUE TITLE
New upcoming hidden option in Click.Option is not hidden from bash completion

### ISSUE THREAD

**Issue by hirenvadalia** [pallets/click#1058]
Thanks for wonderful package.

I don't know whether this is intended behavior or not but I was just trying out new upcoming release 7.0 for hidden option and autocompletion to Click.Option and hidden option hides option from help message but it shows up in bash completion.
However it will be good if we can hide it from bash completion also, so that hidden option is actually hidden from everywhere.

**Comment by davidism** [comment]
@stopthatcow

**Comment by stopthatcow** [comment]
Should be a simple fix. I will take a look this evening.

**Comment by stopthatcow** [comment]
So there is a choice to be made here about behavior. If a param is hidden I agree that tab completions shouldn't reveal the presence of this parameter if it is partially typed in but once a user types it in fully should click allow autocompletion of the parameter's possible values? I lean toward yes, because once a user has typed in the parameter they wish to use it and it should no longer act as "hidden". The same goes for commands and sub commands that are hidden. If a command group is marked as hidden it should not show up un completion results when partially typed in but once typed in all commands under it should complete as normal. I have a prototyped branch working with this behavior, will finish it up tomorrow, rebase and submit a PR.

**Comment by davidism** [comment]
Yes, only stop complain of the token itself.

**Comment by stopthatcow** [comment]
See #1061.
