### ISSUE TITLE
When wrapping text, the first line of a subsequent paragraph is wrong.

### ISSUE THREAD

**Issue by pwhipp** [pallets/click#1066]
In click 6.7, python 3.6.4

This help text for an option:
`'x\n\nI am going to get broken in the wrong place.\n'`

Looks fine:
```
  --test TEXT                     x
                                  
                                  I am going to get broken in the wrong
                                  place.
```

But if we make our first paragraph last line a bit longer:
`'This will break the next paragraph.\n\nI am going to get broken in the wrong place.\n'`

The line position for the first paragraph is carried forward incorrectly when wrapping the first line of the following paragraph so it breaks the line in the wrong place:
```
  --test TEXT                     This will break the next paragraph.
                                  
                                  I am
                                  going to get broken in the wrong place.
```
The result should be:
```
  --test TEXT                     This will break the next paragraph.
                                  
                                  I am going to get broken in the wrong
                                  place.
```

**Comment by chrahunt** [comment]
Also noticed with Click 7.0 Python 3.7.

**Comment by Zarad1993** [comment]
Looking at this.

**Comment by Zarad1993** [comment]
****** Debugging Notes *******
There is a certain width set in here, 

https://github.com/pallets/click/blob/c6042bf2607c5be22b1efef2e42a94ffd281434c/click/formatting.py#L200


If you try setting the width to `100`.  This is the result

<img width="523" alt="Screen Shot 2019-05-06 at 3 52 51 PM" src="https://user-images.githubusercontent.com/18662248/57251137-13c8db80-7017-11e9-98e4-b75d81387f3d.png">


Otherwise, that is an existing bug.
*master*:

<img width="421" alt="Screen Shot 2019-05-06 at 3 53 40 PM" src="https://user-images.githubusercontent.com/18662248/57251169-280cd880-7017-11e9-9e38-38bb2cff2e94.png">


--------

I have a fix in mind for this that is backward compatible and does not affect the usage.
The fix in mind is to only check if new lines (`\n`) come in text. Recalibrate the width based on each line and not on all the lines.


@chrahunt ☝️

**Comment by jcrotts** [comment]
I like your proposed fix, although I'm not sure why the original formatting values were chosen. I'm sure David would be happy to review the PR.

**Comment by Zarad1993** [comment]
@jcrotts - I've got a PR up #1307 . I'll be happy to work on the changes required if needed.

Thanks
