### ISSUE TITLE
Values from envvars are ignored when invoking and forwarding

### ISSUE THREAD

**Issue by chaoflow** [pallets/click#1079]
`foo.py`:
```
import click

@click.group()
def cli():
    pass

@cli.command()
@click.option('--value')
def a(value):
    print(value)

@cli.command()
@click.pass_context
def invoke_a(ctx):
    ctx.invoke(a)
    ctx.parent.invoke(a)

@cli.command()
@click.pass_context
def forward_a(ctx):
    ctx.forward(a)
    ctx.parent.forward(a)

if __name__ == '__main__':
    cli(auto_envvar_prefix='FOO')
```
```
$ FOO_A_VALUE=1 python3 foo.py a
1
$ FOO_A_VALUE=1 python3 foo.py invoke_a
None
None
$ FOO_A_VALUE=1 python3 foo.py forward_a
None
None
```
When invoking and forwarding other commands, I think environment variables (and default maps) should be processed as if the command was directly called, which for both is currently not the case (see also #988 ).

**Comment by dcecile** [comment]
In case anyone needs an example, here's my `invoke` workaround, modelled off the code in [`Context.invoke`](https://github.com/pallets/click/blob/7.1.1/src/click/core.py#L603-L605):

```python
def invoke_with_envvars(ctx, other_command, *args, **kwargs):
    for param in other_command.params:
        if param.name not in kwargs and param.expose_value:
            envvar_value = param.value_from_envvar(ctx)
            if envvar_value is not None:
                kwargs[param.name] = envvar_value
    ctx.invoke(other_command, *args, **kwargs)
```

**Comment by davidism** [comment]
Discussing with @amy-lei This turns out to be way more messy than what was first described. There are a lot of different aspects affecting this.

Click is dynamic. While the common case is for a command to be registered with one group, that's not required. Multiple groups can have the same command object in their `commands` lists. Or they could select a command dynamically by overriding `get_command`. A command does not have a reference to a group it's registered with. So any notion of "as if the command was directly called" is out, as we only know how the command was arrived at in the current context, not other ways it could be arrived at.

In your example, `a` and `invoke_a` are siblings in the same group. So it might seem reasonable to say that `a`, when called from `invoke_a`, should ignore the `invoke_a` name. But neither of the commands know that they're siblings. The context *might* be able to figure that out, but I haven't looked at the code for that.

Imagine instead of a single group, you have a command in one group that forwards to a command in another group. What should the env var be in that case? Remember, invoking and forwarding are completely invisible to the user. All they know is that they called `foo`, not that it internally calls `bar`. It seems like the invoked command shouldn't be part of the env var, but that's the *opposite* behavior of the more specific case of sibling commands.

There's also a difference between `invoke` and `forward`. `forward` passes on command line args, `invoke` does not. I could reasonably argue that `forward` should take into account env vars but `invoke` shouldn't, as `invoke` is separating the command line from the command.

**Comment by davidism** [comment]
The conclusion we reached was that the only reasonable solution right now is to fix the fact that env vars weren't passed at all in `invoke`, but use the full path through the contexts as the name of the var. So in the original example, the name would be `FOO_INVOKE_A_A_VALUE`. This is exactly how names work everywhere else right now.

I could see a case being made for a flag to ignore the current/parent name when building the env var name. By ignoring the parent when calling `invoke`, it would be `FOO_A_VALUE`. By ignoring the command, it would be `FOO_INVOKE_A_VALUE`. For now we'll just fix the general issue.

**Comment by davidism** [comment]
OK, after all that discussion, we had another discussion related to #1124 (prompting from `invoke`) and #950 (type processing from `invoke`), and concluded that the current behavior is intended and shouldn't change. `invoke` occurs in user code, after the command line processing is over, so it should be passed valid Python values that do not need to be processed. See #1124 for a detailed explanation. The command calling `invoke` should define the options on itself that it wants to get from env vars. This also solves the problem of what the name should be, as it could only be the name of the direct command.
