### ISSUE TITLE
File objects implementing the read method

### ISSUE THREAD

**Issue by jongiddy** [pallets/click#1102]
What is the purpose of these lines in the `File` parameter type? https://github.com/pallets/click/blob/b1b8c48345d8accc4dea262b8a41ac5ac1de3af2/click/types.py#L371-L372

In normal operation, when parsing actual command line arguments, `value` will be a string and this code never gets executed. Is there a situation where this code gets called, outside of testing?

I got caught by it while using `testing.CliRunner` and accidentally passing a `py.path.local` from Pytest's `tmpdir` fixture. The `py.path.local` object does have a `read` method, and hence the test used that method to read Unicode strings instead of the byte strings expected for the `File('rb')` parameter.

I fixed this in the test by properly wrapping the `py.path.local` with `str()`, but, due to this special case handling, it took me a while to understand how this had gone wrong.

So, would it make sense to:
1. remove this code from the `File` class?
2. have `CliRunner` convert all arguments to strings, to ensure tests are more like normal operation?

**Comment by davidism** [comment]
When a parameter takes its default value, it passes it through `ParamType.convert` to ensure the default value matches the type. While probably not recommended, the default for a `File` type could be a file-like object, such as when specifying a `default_map` override when calling `main`. While not particularly intended, it also allows passing non-string objects to `args`, such as in tests or when invoking Click from a larger application rather than the command line. Black recently ran into something related to this because its TOML parser converted some data and passed it to Click.

The check is for `read` or `write` methods rather than `isinstance(io.IOBase)` because it should accept duck-typed file-like objects, not only io subclasses. This is not consistent across all types yet, but it's an intended behavior.

This seems more like a design issue with `py.path.local`. Around the time of this report, pytest moved to `tmp_path` which returns a `pathlib.Path` instead, I'd suggest using that going forward.
