### ISSUE TITLE
Having an option to call a list of callbacks for validation

### ISSUE THREAD

**Issue by vijayantajain** [pallets/click#1127]
I think it would be nice to have the option to call multiple validation callbacks instead of just 1 for a command in the `callback` parameter of `option`.

Example - I have `file_path` parameter for a function for which I want to validate that the 1) the path to the file exists. 2) the file exists, and 3) the file is of right format. If I group the validation, it becomes difficult to raise clean errors and also the code becomes less modular. 

Having callbacks to check file path can then also be used for other parameters.

**Comment by davidism** [comment]
I'm not clear why a wrapper function isn't acceptable, you could even use a factory to automate it.

```python
def multi(*callbacks):
    def cb(ctx, param, value):
        out = []
        for callback in callbacks:
            out.append(ctx.invoke(callback, **ctx.params))
        return out
    return cb

@click.option("-a", callback=multi(x, y, z))
```

Or you can subclass command to take a list of callbacks.

```python
class MultiCallbackCommand(click.Command):
    def invoke(self, ctx):
        if self.callback:
            out = []
            for callback in self.callback:
                out.append(ctx.invoke(callback, **ctx.params))
            return out
```

These examples also show that it's not clear what should happen with return values. They return a list, but there are other ways you could handle it.

Since there are methods to customize Click's behavior with this already, I don't think this should be implemented at this time.
