### ISSUE TITLE
nargs=-1 with subcommands

### ISSUE THREAD

**Issue by aprowe** [pallets/click#1153]
Hello, 

When i am using nargs=-1 on an argument on a command group, 
It will not detect which subcommand I am calling, and consumes the subcommand argument.

```python
import click

@click.group()
@click.argument('args', nargs=-1)
def cli(args):
    pass

@cli.command()
def cmd():
    pass

cli()
```

```bash
$ python3 test.py cmd arg1 arg2
Usage: test.py [OPTIONS] [ARGS]... COMMAND [ARGS]...

Error: Missing command.

$ python3 test.py cmd
Usage: test.py [OPTIONS] [ARGS]... COMMAND [ARGS]...

Error: Missing command.

$ python3 test.py arg1 arg2 cmd
Usage: test.py [OPTIONS] [ARGS]... COMMAND [ARGS]...

Error: Missing command.
```

Is there anyway to do this better?
There is preprocessing that is done with the list of args before going to the subcommand, 
so I want the nargs list to be in the group. I also dislike how the command would come after the arg list. is there a way to get syntax `test.py COMMAND [ARGS]...` while passing ARGS through a common function before being passed to the subcommand?

 thanks!

**Comment by davidism** [comment]
`nargs=-1` implies "capture all remaining values". There's no direct way to say "capture all args, except check each one to see if it matches the next (possibly dynamically generated) command name."

As to the order of commands and args, this is intentional. Click requires specifying parameters directly after the command they belong to.

It sounds like you just want to add the argument to the command rather than the group.
