### ISSUE TITLE
How to implement "help <command>"? 

### ISSUE THREAD

**Issue by techtonik** [pallets/click#1206]
I haven't found the code to implement help in this manner:

1. `<command> -h`
2. `<command> --help`
3. `help <command>`
4. `help <command> -h`
5. `help <command> --help`
6. `help`

There 4. 5. 6. are equivalent to `help -h` or `help --help`.

Is there a way to do this?
Is there a way to do this without too much magic?

Taken from https://github.com/pypa/pip/issues/4659 thread.

**Comment by davidism** [comment]
Use `cli.get_command()` to get a command by name. A `Command` has a `get_help()` method.

```python
import click

cli = click.Group()


@cli.command()
def a():
    """Command A"""


@cli.command()
def b():
    """Command B"""


@cli.command()
@click.argument("name")
@click.pass_context
def help(ctx, name):
    command = cli.get_command(ctx, name)
    click.echo(command.get_help(ctx))


if __name__ == "__main__":
    cli()
```

This is just the simplest example. It doesn't check if the name actually exists. It could use a custom `ParamType` that validates the arg and returns the command rather than doing it inside the help command. It could pass the relevant `cli` object in the context rather than needing it globally accessible. Etc.

**Comment by techtonik** [comment]
Here https://click.palletsprojects.com/en/7.x/documentation/

**Comment by davidism** [comment]
@techtonik please see my comments on the linked pip issue.

Please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
