### ISSUE TITLE
Document Python 3.7 behaviour in "Python 3 Surrogate Handling" documentation

### ISSUE THREAD

**Issue by adamtheturtle** [pallets/click#1212]
http://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling rightly warns about issues when using Python 3.

A ``RuntimeError`` is documented.

The good news is that this `RuntimeError` no longer is a problem in Python 3.7, as demonstrated below.

This took some experimentation to find out, and as a user I would have liked to see this in the documentation.

Thank you!

```
~/Desktop ~> echo $LANG

~/Desktop ~> echo $LC_ALL

~/Desktop ~> cat example.py
import click

@click.command()
def hello():
    pass

hello()
~/Desktop ~> vf activate python-3.5.6
~/Desktop (python-3.5.6) ~> python --version
Python 3.5.6
~/Desktop (python-3.5.6) ~> python example.py
Traceback (most recent call last):
  File "example.py", line 7, in <module>
    hello()
  File "/Users/adam/.virtualenvs/python-3.5.6/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adam/.virtualenvs/python-3.5.6/lib/python3.5/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/Users/adam/.virtualenvs/python-3.5.6/lib/python3.5/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales were
discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
~/Desktop (python-3.5.6) ~> vf activate py37 
~/Desktop (py37) ~> python --version
Python 3.7.2
~/Desktop (py37) ~> python example.py
~/Desktop (py37) ~> 
```

**Comment by davidism** [comment]
The advice remains the same though: you should properly configure `LANG`, even though Python 3.7 is nicer about figuring it out. Pull requests welcome, but I'm not really clear what needs to be different about those docs.

**Comment by adamtheturtle** [comment]
Thank you for the response @davidism .

Perhaps I do not understand the full scope of the issues. Why do I need to configure `LANG` if I am on Python 3.7? Perhaps there is an error that will show up with unset `LANG` that I am not aware of.

**Comment by davidism** [comment]
Because the fact that it's not configured is still an issue in general for any program that doesn't do what Python 3.7 does, just like Click on Python 3.6 warns you about.

**Comment by adamtheturtle** [comment]
The context here is the following:

* We have a CLI which is built with Click.
* We ship a binary created with PyInstaller.
* A user reported that on their machines our application raised the ``RuntimeError`` and they would prefer to not change their setup.
* It took some time to find that if we built our Click application using Python 3.7, the user would not get the error.
* I thought that if this had been clear from the Click documentation, I would have saved some time.

**Comment by davidism** [comment]
I'd be happy to review a pull request that adds a mention of Python 3.7 and the relevant PEPs that changed this behavior.

**Comment by WouterDX** [comment]
Happy to contribute because I also spend today working through this problem. 
In the very least, pointing to the PEP 538 and PEP 540 solutions for python 3.7 instead of pointing to the various problematic discussions would help.

And exception handling seems to be confusing as well. Printout below (breakclick.py is same as example.py) shows that setting LC_CTYPE to something unknown gives a wrong error message.
This is something that can happen by ssh'ing to a machine and overruling its locale setting. In other words, it won't help if that machine was configured well in the first place.
`# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
# python breakclick.py
# LC_CTYPE="C" python breakclick.py
Traceback (most recent call last):
  File "breakclick.py", line 7, in <module>
    hello()
 ...
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.p                                                                                       alletsprojects.com/en/7.x/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales were
discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, af_ZA.utf8, am_ET.utf8, an_ES.utf8, ar_AE.utf8, ar_BH.utf8, ar_DZ.utf8, ar_EG.utf8, ar_IN.utf8, ar_IQ.                                                                                       utf8, ar_JO.utf8, ar_KW.utf8, ar_LB.utf8, ar_LY.utf8, ar_MA.utf8, ar_OM.utf8, ar_QA.utf8, ar_SA.utf8, ar_SD.utf8, ar_SY.utf8, ar_TN.utf8, ar_YE.utf8,                                                                                        as_IN.utf8, ast_ES.utf8, az_AZ.utf8, be_BY.utf8, ber_DZ.utf8, ber_MA.utf8, bg_BG.utf8, bn_BD.utf8, bn_IN.utf8, bo_CN.utf8, bo_IN.utf8, br_FR.utf8, bs_                                                                                       BA.utf8, byn_ER.utf8, ca_AD.utf8, ca_ES.utf8, ca_FR.utf8, ca_IT.utf8, crh_UA.utf8, cs_CZ.utf8, csb_PL.utf8, cv_RU.utf8, cy_GB.utf8, da_DK.utf8, de_AT.                                                                                       utf8, de_BE.utf8, de_CH.utf8, de_DE.utf8, de_LU.utf8, dv_MV.utf8, dz_BT.utf8, el_CY.utf8, el_GR.utf8, en_AG.utf8, en_AU.utf8, en_BW.utf8, en_CA.utf8,                                                                                        en_DK.utf8, en_GB.utf8, en_HK.utf8, en_IE.utf8, en_IN.utf8, en_NG.utf8, en_NZ.utf8, en_PH.utf8, en_SG.utf8, en_US.utf8, en_ZA.utf8, en_ZW.utf8, es_AR.                                                                                       utf8, es_BO.utf8, es_CL.utf8, es_CO.utf8, es_CR.utf8, es_DO.utf8, es_EC.utf8, es_ES.utf8, es_GT.utf8, es_HN.utf8, es_MX.utf8, es_NI.utf8, es_PA.utf8,                                                                                        es_PE.utf8, es_PR.utf8, es_PY.utf8, es_SV.utf8, es_US.utf8, es_UY.utf8, es_VE.utf8, et_EE.utf8, eu_ES.utf8, fa_IR.utf8, fi_FI.utf8, fil_PH.utf8, fo_FO                                                                                       .utf8, fr_BE.utf8, fr_CA.utf8, fr_CH.utf8, fr_FR.utf8, fr_LU.utf8, fur_IT.utf8, fy_DE.utf8, fy_NL.utf8, ga_IE.utf8, gd_GB.utf8, gez_ER.utf8, gez_ET.ut                                                                                       f8, gl_ES.utf8, gu_IN.utf8, gv_GB.utf8, ha_NG.utf8, he_IL.utf8, hi_IN.utf8, hne_IN.utf8, hr_HR.utf8, hsb_DE.utf8, ht_HT.utf8, hu_HU.utf8, hy_AM.utf8,                                                                                        id_ID.utf8, ig_NG.utf8, ik_CA.utf8, is_IS.utf8, it_CH.utf8, it_IT.utf8, iu_CA.utf8, iw_IL.utf8, ja_JP.utf8, ka_GE.utf8, kk_KZ.utf8, kl_GL.utf8, km_KH.                                                                                       utf8, kn_IN.utf8, ko_KR.utf8, kok_IN.utf8, ks_IN.utf8, ku_TR.utf8, kw_GB.utf8, ky_KG.utf8, lg_UG.utf8, li_BE.utf8, li_NL.utf8, lo_LA.utf8, lt_LT.utf8,                                                                                        lv_LV.utf8, mai_IN.utf8, mg_MG.utf8, mi_NZ.utf8, mk_MK.utf8, ml_IN.utf8, mn_MN.utf8, mr_IN.utf8, ms_MY.utf8, mt_MT.utf8, my_MM.utf8, nb_NO.utf8, nds_                                                                                       DE.utf8, nds_NL.utf8, ne_NP.utf8, nl_AW.utf8, nl_BE.utf8, nl_NL.utf8, nn_NO.utf8, no_NO.utf8, nr_ZA.utf8, nso_ZA.utf8, oc_FR.utf8, om_ET.utf8, om_KE.u                                                                                       tf8, or_IN.utf8, pa_IN.utf8, pa_PK.utf8, pap_AN.utf8, pl_PL.utf8, ps_AF.utf8, pt_BR.utf8, pt_PT.utf8, ro_RO.utf8, ru_RU.utf8, ru_UA.utf8, rw_RW.utf8,                                                                                        sa_IN.utf8, sc_IT.utf8, sd_IN.utf8, se_NO.utf8, shs_CA.utf8, si_LK.utf8, sid_ET.utf8, sk_SK.utf8, sl_SI.utf8, so_DJ.utf8, so_ET.utf8, so_KE.utf8, so_S                                                                                       O.utf8, sq_AL.utf8, sq_MK.utf8, sr_ME.utf8, sr_RS.utf8, ss_ZA.utf8, st_ZA.utf8, sv_FI.utf8, sv_SE.utf8, ta_IN.utf8, te_IN.utf8, tg_TJ.utf8, th_TH.utf8                                                                                       , ti_ER.utf8, ti_ET.utf8, tig_ER.utf8, tk_TM.utf8, tl_PH.utf8, tn_ZA.utf8, tr_CY.utf8, tr_TR.utf8, ts_ZA.utf8, tt_RU.utf8, ug_CN.utf8, uk_UA.utf8, ur_                                                                                       PK.utf8, ve_ZA.utf8, vi_VN.utf8, wa_BE.utf8, wo_SN.utf8, xh_ZA.utf8, yi_US.utf8, yo_NG.utf8, zh_CN.utf8, zh_HK.utf8, zh_SG.utf8, zh_TW.utf8, zu_ZA.utf                                                                                       8

Click discovered that you exported a UTF-8 locale
but the locale system could not pick up from it because
it does not exist.  The exported locale is "en_US.UTF-8" but it
is not supported
# LC_CTYPE="en_US.UTF-8" python breakclick.py
`

**Comment by michaelkarlcoleman** [comment]
Ran into this issue today, and it's quite exasperating.  Is there truly no way that Click can "just work" when LANG=C?  Just aborting with "your system is misconfigured" doesn't seem useful (nor even true).

Using Unicode characters on the command line seems rather dubious in the first place...

**Comment by davidism** [comment]
I believe earlier comments in this and previous issues have addressed our stance on this. We do not plan to change this behavior. As I've stated, I'd be happy to review PRs that improve the documentation or error messages.

**Comment by davidism** [comment]
Docs updated in #1334
