### ISSUE TITLE
Setting to show options on completion even without minus

### ISSUE THREAD

**Issue by schollii** [pallets/click#1220]
Tab completion by default lists subcommands and choices but lists options only if at least a dash has been provided. Would it be possible to have a setting in Click that would show options too even if no dash provided? Example: 
```
$ command <TAB><TAB>
 --help --rev --shallow -r foo bar baz
```
If you show me the file where this if/else dash-present is tested I can git it a shot.

**Comment by davidism** [comment]
That's not how completion seems to work with the programs I tested. For example, `git` has some global options, but they don't appear when tab completing `git <tab>`, only `git -<tab>`. I don't want to add an option for this unless there's a very good reason to, as the convention seems to be otherwise.

**Comment by schollii** [comment]
I have checked a few commands (kubectl, kops, terraform, helm, aws, python) and you are right, sorry for the noise, closing this.
