### ISSUE TITLE
commands in separate files

### ISSUE THREAD

**Issue by schollii** [pallets/click#1228]
I would like to have commands in separate modules. I'm thinking the most maintainable approach is to use `click.CommandCollection`. For example given a module mylib.py:
```
# mylib.py
import click

@click.group()
def commands():
    pass

@commands.command()
def cmd1():
   ...
...
@commands.command()
def cmdN():
   ...
```
then a script main.py could do this: 
```
# main.py
import click, mylib

@click.group()
def main_group(): pass

@main_group.command()
def main_cmd1(): pass

main = click.CommandCollection([main_group, mylib.commands])
main()
```
This seems to work well BUT the documentation for `CommandCollection` says this is not "as recommended":

> it can also be interesting to merge multiple together into one script. While this is generally not as recommended as it nests one below the other, the merging approach can be useful in some circumstances for a nicer shell experience.

What is meant by "not as recommended as it nests one below the other", what could be some possible gotchas to that approach? Is this the right approach for having commands in separate modules?

**Comment by jcrotts** [comment]
Your approach seems okay to me. I think the recommendation is suggesting that you should use `Custom Multi Commands` instead of nesting your multi commands. In my opinion general nesting commands makes things more difficult to reason about, and should generally be used only if you need it.

I am going to close this for now, but if you think the docs are insufficient in this area please open a PR.

I have used the `add_command()` function to do this in the past.
https://click.palletsprojects.com/en/7.x/quickstart/#nesting-commands

Also see:
https://stackoverflow.com/questions/34643620/how-can-i-split-my-click-commands-each-with-a-set-of-sub-commands-into-multipl

**Comment by schollii** [comment]
Thanks @jcrotts but it's not clear to me what that would look like, any code I could look at to exemplify what you are describing (I presume one custom mutli command in each file)?

**Comment by schollii** [comment]
I looked at the links. The main disadvantage of add_command compared to CommandCollection is that you have to manually add your commands, this is easy to forget. Whereas with CommandCollection you just have to remember to add the top level group of each file which really only happens once per file that you define commands in. 

But I'm intrigued by the third option you mention, custom multi-command. Do you know of code that uses this approach?

**Comment by jcrotts** [comment]
I'll see if I can find some. I would ask this on Stack Overflow, you might get better traction over there.

If you think the docs are missing info on this, or have a feature request happy to review a PR as well.
