### ISSUE TITLE
Add timeouts to termui getchar tests which can block and wait on certain special characters

### ISSUE THREAD

**Issue by sirosen** [pallets/click#1326]
#1108 improved the handling of certain special characters on Windows. In the discussion, we noted that `àH` and "up arrow" are indistinguishable. As a result, if you use getchar on Windows and type `à`, getchar will wait indefinitely for a second character of input.
(This is the behavior we chose in #1108.)

Thanks to #1315, there are a few nice tests of Windows getchar behavior at the bottom of `tests/test_termui.py`. However, if someone is working on these tests, or working on getchar itself, it's conceivable that those tests would block and wait forever -- this is bad feedback to get from the testsuite.
If we put a timeout on these tests -- I would go with a generous 5s, or even something shorter -- then if getchar breaks or those tests are altered incorrectly, the test will fail in reasonable time.

To do this, the following seems like a good course:
- add pytest-timeout to testing dependencies
  - update tox.ini
  - ensure any doc on non-tox testing gets pytest-timeout installed
- add timeouts to the relevant getchar tests
- modify those tests to send a crafted "bad input" like `à`, and verify that they abort via timeout
  - don't commit this modification, or, if you're relying on appveyor to test your change, ensure that you reset and force-push to remove this commit

**Comment by andrewzu** [comment]
I did some investigation and it seems the "wait indefinitely" behavior doesn't apply to the testing scenarios. I would suggest close this ticket.

`getchar()` waits indefinitely with inputs like 'à' due to `msvcrt.getwch()` or `msvcrt.getwche()` waiting for user to input the second char.  

When testing Windows inputs for `getchar` (as done in #1315), one would monkeypatch  `getwch` or `getwche` to simulate user input to `getchar`. Unless intentionally monkeypatch those functions to wait indefinitely, the patched `getwch, getwche` always return a value or throw an exception (e.g. when input queue exhausted). Therefore, adding timeout is not needed.

**Comment by sirosen** [comment]
I think you're right for the most part, and that I got my thinking tripped up. I was obviously thinking that if someone sent `à` in a test, we'd see the "real" behavior and the testsuite would hang. But as the tests are written, with the `msvcrt` functions patched, that wouldn't happen.

The only realistic scenario I can think of in which these tests hang and timeouts are valuable would be changes to the implementation of `getchar`. That's not nearly so much of a minefield as what I was thinking this would be.

I'm going to close this as not necessary. @andrewzu, thanks for looking into this and correcting my mistake!
