### ISSUE TITLE
Testing Infinite Running applications.

### ISSUE THREAD

**Issue by Liamdoult** [pallets/click#1375]
I am currently using click to interface flask. 

i.e.
``` 
$ python app.py web-interface
 * Serving Flask app "text_alignment.api_interface" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:4000/ (Press CTRL+C to quit)
```
How would I test an application that would require termination to get the output.

As expected, this will stall as line 4 will never be reached:
```                                                                              
def test_flask_run():                                                           
    runner = CliRunner()                                                        
    result = runner.invoke(cli.run, ['web-interface'])                                   
    assert result.output == 'flask'
```

Thanks.

**Comment by davidism** [comment]
Mock the function that starts the server and test that the command does the other things you need it to. Or don't test `run` because that's already tested in Flask. Or use `pytest-xprocess` and kill it after a few seconds.

Please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).

**Comment by Liamdoult** [comment]
Thanks
