### ISSUE TITLE
Password / hidden prompts should have option to display asterisks

### ISSUE THREAD

**Issue by chaoflow** [pallets/click#1424]
For password / hidden prompts it would be great if instead of displaying nothing one could display one (or more) asterisk per character entered.

What do you think about this feature? I'd be happy to implement it.

**Comment by juped** [comment]
@mwizasimbeye11 and @teymour-aldridge will be working on this!

**Comment by davidism** [comment]
After investigating, this turned out to be a lot more complex than it sounds. Right now, we rely on Python's built-in `getpass()` to get hidden input securely. To implement our own, we'd need to get each character individually and echo something else, which adds a lot of extra code to maintain that could fail in weird ways. Also, it's not clear what the security implications are for implementing our own instead of `getpass`. Since this is a relatively minor cosmetic change, I don't think it's worth the added maintenance.

I know you offered to submit a PR, if you do come up with one I'm happy to consider it, but for now I'm going to close this.

There is also the [stdiomask](https://github.com/asweigart/stdiomask) library that provides this, but I'm not sure of its security implications either. It's GPL, so we couldn't use its code in Click, and we also can't rely on external dependencies, which is why #1579 wasn't merged.

**Comment by jab** [comment]
For reference, just found an [open issue for adding this option to `getpass()` itself](https://bugs.python.org/issue32884), with the notable support of Steven D’Aprano. It would likely be many years from now, but if/when this is available in the minimum Python version that Click supports, it’s possible we’ll reconsider this.
