### ISSUE TITLE
is there a nice way to test click auto-completion functions?

### ISSUE THREAD

**Issue by seebi** [pallets/click#1453]
The current documentation is blank about this.
Is there maybe an example somewhere?

**Comment by davidism** [comment]
Looks like the test for autocompletion itself uses a somewhat internal function: https://github.com/pallets/click/blob/master/tests/test_bashcomplete.py

Or test your autocompletion function, since Click's internals are already tested. An autocompletion function takes a `Context`, list of full arguments, and the partial string being completed, all of which you can fake in a test.

Or if you're using `CliRunner`, you can call `invoke(..., env={"_FOO_COMPLETE": "source"}, prog_name="foo")` along with partial arguments and look at the output.

**Comment by seebi** [comment]
When I start it like this, I actually do not get my function output but something like

'''
_cmemc_completion() {
    local IFS=$'
'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _CMEMC_COMPLETE=complete $1 ) )
    return 0
}

_cmemc_completionetup() {
    local COMPLETION_OPTIONS=""
    local BASH_VERSION_ARR=(${BASH_VERSION//./ })
    # Only BASH version 4.4 and later have the nosort option.
    if [ ${BASH_VERSION_ARR[0]} -gt 4 ] || ([ ${BASH_VERSION_ARR[0]} -eq 4 ] && [ ${BASH_VERSION_ARR[1]} -ge 4 ]); then
        COMPLETION_OPTIONS="-o nosort"
    fi

    complete $COMPLETION_OPTIONS -F _cmemc_completion cmemc
}

_cmemc_completionetup;
'''

Do I miss something here?

**Comment by davidism** [comment]
Nope, that's what autocompletion dies, then the your takes that and actually handles the completion.

**Comment by seebi** [comment]
Ok, got it ... using

```
from click._bashcomplete import get_choices

def choices_without_help(cli, args, incomplete):
    completions = get_choices(cli, 'cmemc', args, incomplete)
    return [c[0] for c in completions]

def test_delete_completion():
    assert choices_without_help(cli, ['graph', 'delete'], 'acc') == ['...']
```

actually does the job.... nice.

And thanks @davidism

**Comment by davidism** [comment]
Follow up to this, I mistyped. `_PROG_NAME_COMPLETE=complete`, not `source`, will make Click output the available completions. `source` outputs the shell function that enables completion, and you can see it calling Click with `complete`. Either way works for testing.
