### ISSUE TITLE
Atomic writes throw an error when writing to docker mounted file

### ISSUE THREAD

**Issue by mikegedelman** [pallets/click#1512]
# Expected Behavior

Click should write to the file normally without throwing an error.

```python
import click

# out.txt is a file mounted directly in docker (ie, only it is mounted, not its parent directory)
# like this: docker run -v `pwd`/out.txt:/work/out.txt click-err
def main():
    f = click.open_file("out.txt", "w", atomic=True)
    f.write("test")
    f.close()

if __name__ == "__main__":
    main()
```

This repository sets up the whole scenario in docker and reproduces the issue
https://github.com/mikegedelman/click-atomic-write-error

I also verified that writing to these files using stdlib functions works normally.

### Actual Behavior

Click thows this error when calling f.close()

```pytb
Traceback (most recent call last):
  File "/work/main.py", line 11, in <module>
    main()
  File "/work/main.py", line 7, in main
    f.close()
  File "/usr/local/lib/python3.7/site-packages/click/_compat.py", line 619, in close
    _replace(self._tmp_filename, self._real_filename)
OSError: [Errno 16] Device or resource busy: '.__atomic-writee31adfb9' -> '/work/out.txt'
```

### Environment

* Python version: 3.7.3
* Click version: 7.1.1

**Comment by jcrotts** [comment]
Thanks for posting this issue, and providing an example.

I'm guessing this is a permissions issue with docker, the process probably doesn't have the correct permissions to write to a temporary file in the directory where out.txt is located.

What host OS are you using with docker?

**Comment by mikegedelman** [comment]
I'm currently using macOS Catalina 10.15.5 with Docker Desktop 2.3.0.3, and I still can reproduce the error in my example repo.

**Comment by davidism** [comment]
Atomic writes don't write directly to a file, they write to a temporary file then replace the existing file. Does `mv tmpfile /work/out.txt` in your Docker work? Does `os.replace(...)` from a Python console in your Docker work?

**Comment by jcrotts** [comment]
Both of the commands David suggested give the same "Device or resource busy", so I don't think this is a problem with click, but a result of the way docker handles file mounts.

You can work around this by mounting the directory that contains your file instead of the file itself.
cp and shell redirects also still work.

According to [this](https://unix.stackexchange.com/questions/404189/find-and-sed-string-in-docker-got-error-device-or-resource-busy) SO post docker doesn't let you change the inode of file volumes from inside the docker container.
