### ISSUE TITLE
click.argument cannot handle negative numbers

### ISSUE THREAD

**Issue by CloudNiner** [pallets/click#1624]
### Expected Behavior

I should be able to pass a negative number to a `click.argument`. I get the same error below if I attempt to parse a negative number as `type=str` or `type=float`. `click.option` works as expected. 

```python
import click


@click.command()
@click.argument("num", type=int)
def main(num):
    print(num)


if __name__ == "__main__":
    main()

```

### Actual Behavior

Tell us what happens instead.

```pytb
> python click_test.py -4
Usage: click_test.py [OPTIONS] NUM
Try 'click_test.py --help' for help.

Error: no such option: -4
```

### Environment

* Python version: 3.7.7
* Click version: 7.1.2

**Comment by davidism** [comment]
This isn't a Click issue, it's a general shell quoting issue. Quote values that look like command line syntax: `python click_test.py '-4'`.

**Comment by CloudNiner** [comment]
I get the same error if I quote with single or double quotes in both zsh and bash.

A test program that uses argparse generates the expected output:
```python
import argparse

parser = argparse.ArgumentParser(description="Process an integer.")
parser.add_argument("integer", type=int, help="an integer")

args = parser.parse_args()
print(args.integer)

```
```
> python argparse_test.py -4
-4
```

**Comment by davidism** [comment]
Sorry, was thinking of escaping shell expansion. For arguments, you'll need to specify them after the `--` flag to turn off option parsing: `example.py -- -4`, or ignore unknown options. https://click.palletsprojects.com/en/7.x/arguments/?highlight=ignore_unknown_options#option-like-arguments Otherwise it's not possible to unambiguously identify "-2" as an argument value instead of an invalid option name.

**Comment by CloudNiner** [comment]
👍 thanks for the explanation
