### ISSUE TITLE
Inconsistncy with raising a click.UsageError with bad subcommand names

### ISSUE THREAD

**Issue by Dylan-Brotherston** [pallets/click#1626]
When a subcommand isn't given to a `click.group` no exception is generated, instead the program exits.
When a non-existent subcommand is given to a `click.group` a `click.UsageError` is generated.
Because of this even with `standalone_mode=False` it is impossible to internally handle this error, eg to display a custom error.

### Expected Behavior

```python
@click.group()
def cli():
    pass

@cli.command()
def subcommand1():
        pass

@cli.command()
def subcommand2():
        pass

if __name__ == "__main__":
        try:
                cli(standalone_mode=False)
        except click.UsageError as e:
                print(e.format_message())
                # $ ./prog subcommand3
                # No such command 'subcommand3'.
                # $ ./prog
                # No command given, possible commands (subcommand1 subcommand2)
```

### Actual Behavior

```python
@click.group()
def cli():
    pass

@cli.command()
def subcommand1():
        pass

@cli.command()
def subcommand2():
        pass

if __name__ == "__main__":
        try:
                cli(standalone_mode=False)
        except click.UsageError as e:
                print(e.format_message())
                # $ ./prog subcommand3
                # No such command 'subcommand3'.
                # $ ./prog
                # $ # No exception, process exit.
```

### Environment

* Python version: 3.7.8
* Click version: 7.1.2

At [`core.py:1243`](https://github.com/pallets/click/blob/228ca13778af1c2b1fe20191804dfacb09b8586a/src/click/core.py#L1243) click calls `ctx.exit()`

## Proposed Solution

One possible patch would be as follows
```patch
@@ -1240,4 +1240,3 @@
     def parse_args(self, ctx, args):
         if not args and self.no_args_is_help and not ctx.resilient_parsing:
-            echo(ctx.get_help(), color=ctx.color)
-            ctx.exit()
+            raise UsageError(f"No command given, possible commands ({' '.join(list(ctx.command.commands.keys()))})", self)
```

**Comment by jab** [comment]
It's not clear that invoking with no subcommand should be treated the same as invoking with an invalid subcommand, and should therefore be an error.

As you've seen, currently, Click intentionally defaults to not treating this as an error, as if you'd explicitly passed `no_args_is_help=True` to your `click.group()` call.

If you pass `no_args_is_help=False` instead, you'll get the behavior you're looking for. I'm going to close this assuming that's what you're looking for.

Also, you haven't mentioned the exit code at all, but #1394 may be of interest to you as well, since it wants Click to treat the `no_args_is_help=True` case as an error by default (i.e. the command should exit nonzero).
