### ISSUE TITLE
if default given, it should be shown in the help

### ISSUE THREAD

**Issue by schollii** [pallets/click#1652]
### Expected Behavior

If I specifiy a default in an option that is different from the "default default", it's probably because the "default default" is not adequate, so I should see it in the --help output, without having to write "show_default=True". I understand that if default is *not* given, or matches the default default, then show_default can default to false. 

But there's nothing wrong with stating the obvious either: although most people expect defaults to be 0/None/False (falsy), it's not BAD to show it in the help, even if it is a default default and is "obvious". Whenever I use --help on an app, I never think "duh that default value is obvious, why do they bother showing it", but I often think "gosh I wish they had stated that the default was None (or ABC or whatever) because it actually was not obvious". 

### Actual Behavior

You have to specify show_default=True for it to become visible if default if default is not the default default. When have you ever seen a CLI not show "non-null" defaults (ie defaults other than 0/None/False are always visible). The show_default=True should be implied if the default given does not match the "default default"

### Environment

* Python version: 3.7
* Click version: 7.1.2

**Comment by davidism** [comment]
"default default" is not a concept in Click, I'm not clear what this is referring to. You can enable showing defaults globally by setting `show_default=True` on the context instead of individual commands.

I appreciate that you're interested in improving Click, but your issues are generally closed rather than acted on. Perhaps it would be easier to ask questions about using Click on our Discord first? https://discord.gg/pallets That could help you determine if an issue you're facing is a good fit for an issue for Click.
