### ISSUE TITLE
Option with unknown number of parameters

### ISSUE THREAD

**Issue by saroad2** [pallets/click#1658]
While the `click.argument` decorator supports an unknown number of arguments (with specifying `nargs=-1`), `click.option` does not. I would like to add this feature.

My use case is that I want to insert an array of values with an unknown length. The CLI command should look like:
```
calculate sum --array 1 4.5 9
calculate multiply --array 0 3
```

The current API of using `multiple=True` doesn't fit for this kind of CLIs, and looks like:
```
calculate sum --array 1 --array 4.5 --array 9
calculate multiply --array 0 --array 3
```

Using `click.argument` instead of `click.option` seems to me like an unnecessary compromise, and I think it makes the CLI command less clear.

What do you think?

**Comment by davidism** [comment]
Due to the way the parser works, this is not possible. It may become possible as we consider a larger refactor in #590.

This is called out (briefly) in the docs: https://click.palletsprojects.com/en/7.x/options/?highlight=nargs#multi-value-options

> For options, only a fixed number of arguments is supported.

Arguments can have `nargs=-1`, perhaps it's possible to restructure your CLI to use an argument instead. Or, if you're willing to make a custom type, you could accept a single (quoted) string of separated values and split the string:

```
calculate sum --array "1, 2, 3, 4"
```
