### ISSUE TITLE
Confusing behavior with using enviornment variables for group level options

### ISSUE THREAD

**Issue by xinbinhuang** [pallets/click#1694]
Two issues:
-  In general, Group level command option provided from the environment only takes effect when the command is provided. I am not sure if this is a bug or by design.
- When we use `version_option` with env variable, the behavior gets a bit extra confusing. (see below)

```python
# cli.py
import click


@click.group()
@click.version_option(version=1)
def cli():
    "CLI tool"


@cli.command()
@click.option("--username")
def greet(username):
    click.echo("Hello %s!" % username)


if __name__ == "__main__":
    cli(auto_envvar_prefix="GREETER")
```

### Expected Behavior

```bash
$ export GREETER_VERSION=true
$ python cli.py 
test.py, version 1

$ python cli.py greet
test.py, version 1     # maybe we should just ignore this line
Hello, None!
```

### Actual Behavior

Tell us what happens instead.

```pytb
$ python cli.py
Usage: test.py [OPTIONS] COMMAND [ARGS]...

  CLI tool

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  greet

$ python cli.py greet
test.py, version 1
```

### Environment

* Python version: 3.7
* Click version: 7.1.2

**Comment by davidism** [comment]
Choosing `--version` for the examples wasn't particularly helpful, as `version_option` has less common behavior. 
The second call (`example --version greet`) shows only the version because `version_option` exits after showing the version, it's not meant to keep going.

The first call shows help and exits because no args are passed on the command line. The first thing `Group` does if no args are present is show help (unless `no_args_is_help` is disabled). It only parses its own arguments and resolves values from other sources after that. Again, using `--version` doesn't make much sense here because you really wouldn't expect to pass its value as an env var.
