### ISSUE TITLE
Question: how to extend intelligent file handling with click's type system in a sane way?

### ISSUE THREAD

**Issue by kratsg** [pallets/click#1711]
Continues from #426 which got locked (why?) so I am submitting a new issue for a follow up question.

@davidism responded with

> I still agree with why this is closed, so I don't plan to reopen it. Click's type system is extensible to facilitate any specific needs a project has.

One current issue is that, depending on the system you're on, you might have CRLF instead of CR / LF for line endings (as an example). For click to support this nicely however, it seems like the current suggestion from that issue is to basically:

1) copy the `click.File` entirely (or inherit it): https://github.com/pallets/click/blob/5eb46cba463ff3e3894b58f6649c5a13f02a70b1/src/click/types.py#L545
2) reimplement the entirety of `convert` in the inherited class, using a reimplemented form of `open_stream` to handle the different line endings: https://github.com/pallets/click/blob/5eb46cba463ff3e3894b58f6649c5a13f02a70b1/src/click/_compat.py#L367

Is this correct? I'm confused by this, since I need the functionality of `click.File`, with something else added on top of it, but I don't have an easy way to implement it without ripping out the existing code and just passing through a keyword argument...

**Comment by davidism** [comment]
As stated in the original closure, it adds complexity for a niche issue in another library that can already be worked around. In this case, the workaround is probably along the lines of "open in binary mode, and wrap with `io.TextIOWrapper` with whatever behavior you need."

**Comment by kratsg** [comment]
How do I incorporate the intelligent file handling on top of this (e.g. "functionality of `click.File`") - as I need to be able to have the program work via piping in the input as well as by passing in a file? Relying only on `io.TextIOWrapper` won't do that alone. What part of `click.File` do I need to get intelligent file handling?

**Comment by davidism** [comment]
Please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).

**Comment by davidism** [comment]
The `File` type can open in binary mode. Subclass it or add a parameter callback or use the command function to wrap the binary file in `TextIOWrapper`.

I get that you had a specific issue, but the problem is that *everyone* has a specific issue, so we constantly get old issues resurrected with someone asking maintainers to put in the work for *their* specific issue. I'm sorry that "process file opened by `click.File` with `csv` accounting for newlines in quoted cells" isn't covered elsewhere, but answering questions like this on the issue tracker does not scale with maintainer time.

Please use Stack Overflow for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve).
