### ISSUE TITLE
Add testing feature for click.edit()

### ISSUE THREAD

**Issue by altendky** [pallets/click#1720]
When testing code that calls `click.edit()` the only presently available hook provided by Click is to specify one of the environment variables to refer to a custom 'editor' that just returns the desired value instead of waiting for a user to actually edit stuff.  This seems both slow from a runtime perspective and a bit of a hassle to achieve when writing a test, especially when dealing across platforms.  I think it would be nice to have a context manager usable in a test to specify either a simple string to be the result or perhaps a function to be called that would return the desired result.

This came up while reviewing https://github.com/twisted/towncrier/pull/275/files#diff-3246fd469cc78dacf0f687c6f8447bea31e24c85778134d0bea2ea546ccc0776R68.

**Comment by davidism** [comment]
I think the most straightforward answer here is to patch `click.edit` to return what you expect.

```python
def test_edit(monkeypatch):
    def edit(*args, **kwargs):
        # possibly assert something about the passed arguments
        return "edited value"

    monkeypatch.setattr(click, "edit", edit)
    ...
```

**Comment by altendky** [comment]
`mock` is already in use in the linked PR.  Elsewhere it was suggested that Click ought to provide the functionality which I figure would improve the likelihood of accuracy of the results in testing vs. just leaving it to each developer to hopefully get it 'right'.  Anyways, this is presumably just the whole to-mock-or-not question which I am not really qualified to take on.

I don't expect anyone else to develop this for me.  Do you think it's specifically a thing Click should not have?  Or should we leave this around in case I find time (or some other lucky dev gets interested).

**Comment by davidism** [comment]
I'm not even clear what support within Click would look like. The context manager you describe is exactly what `monkeypatch` is doing: overriding the function, then resetting it. I'm not really clear why users would get it wrong. I'm not seeing a good enough reason to add something to Click right now.

**Comment by exarkun** [comment]
The thing that this API would do inside Click that a monkeypatch in a downstream project can't do is provide some assurance that it will continue to work.

Consider this scenario.  A future Click developer invents a better way to support assisting with editing files.  They introduce it and deprecate `click.edit`.  However, the downstream project has monkey-patched it and the two changes interact in a way such that downstream developers never see the deprecation warning.  After all, their test suite isn't calling `click.edit`.  Then Click eventually removes `click.edit` and the downstream project is now broken.

There are variations on this.  Perhaps the signature of `click.edit` changes - the downstream project test suite never sees this because of their monkey-patch.  Or the return value changes - perhaps to address some bytes vs unicode considerations.  Maybe there is some encoding or decoding behavior in `click.edit` (if not now, in the future).  All of this is missed by a naive monkey-patch and bugs are given a place to hide.

**Comment by davidism** [comment]
Your hypothetical situation wouldn't be fixed by Click having a patch instead of the test. That's just too hypothetical to consider, I don't see `click.edit` changing as described any time soon. Thanks for your input, I'm going to close this for now.

**Comment by exarkun** [comment]
Thanks for the quick response.  Just for the record, the original issue doesn't suggest that Click should do the monkey-patching.  It just requests a feature from Click.  I too doubt that monkey-patching would be a good way to provide the feature.

I don't need or want this issue re-opened.  I just wanted to leave this information to clarify what is being rejected.
