### ISSUE TITLE
'Group' object has no attribute 'option'

### ISSUE THREAD

**Issue by mBouamama** [pallets/click#1727]
first of all, thx for your jobs, amazing package gg.

### Expected Behavior

I try to learn how to use click and i use groups but i see if you declare option after command line groups don't recognize option

```python
import click


@click.group()
@click.option("--filter")
@click.pass_context
def cli(ctx, filter):
    click.echo("test")
    ctx.ensure_object(dict)
    if filter:
        click.echo("filter")
        ctx.obj['Filter'] = filter


@cli.group()
@click.pass_context
def list(ctx):
    click.echo("list")
    click.echo(ctx.obj)


if __name__ == '__main__':
    cli()
```

```python
python main.py list --filter test
AttributeError: 'Group' object has no attribute 'option'
```
### Actual Behavior

I want to write my option everywhere in my command line (before or after my command
```python
python main.py list --filter test
OK
```

### Environment

* Python version: 3.8
* Click version: 7.1.2

**Comment by davidism** [comment]
You seem to be asking about two different things. Your example works fine, but shows `Error: no such option: --filter`. This is a design decision in Click. You must specify options after the command or group they are defined for, and before any subgroup. There are numerous other discussions on this in the tracker. On the other hand, the error you said you got is because you did `@cli.option()` instead of `@click.option` somewhere, but you didn't show that in your example.
