### ISSUE TITLE
Deprecate click.get_terminal_size() in favor of stdlib shutil.get_terminal_size()

### ISSUE THREAD

**Issue by jdufresne** [pallets/click#1736]
Since Python 3.3, the stdlib provides the function `shutil.get_terminal_size()`. Now that the project has dropped Python 2
support, the compatibility shim is no longer necessary.

The stdlib version returns a named tuple. So rather than indexing "0", can use the more self-documenting attribute "columns".

Docs available at: https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size

**Comment by janLuke** [comment]
Maybe I'm missing something but I don't understand the reason for deprecating `click.get_terminal_size`. Why not just changing its internal implementation? 

There's an advantage in defining a "wrapper function" for something you use across your code base: it allows to change implementation without changing all the places where it is used (as long as its interface is the same). In fact, it's the same reason you could have changed just the implementation if you'd not decided to replace all `[0]` with `.columns`.

Furthermore, people may have used that function. Why creating a backward incompatibility?

**Comment by davidism** [comment]
We deprecate things, that's not going to change. I don't have a desire to maintain copies of things that are supported by Python itself.

We've done deprecations plenty of times in all the Pallets projects, removing or changing behavior. This isn't even the only one in the next version of Click. Users will see a `DeprecationWarning` while running tests, have the opportunity to update their code, then it will be removed in a future version. Projects should also pin their dependency versions to control when and how they do updates and address changes.

**Comment by janLuke** [comment]
@davidism I'm not against all deprecations. I just don't see the advantage of deprecating this particular function. 

There's no cost at all in maintaining a wrapper function of `click.get_terminal_size`; actually using wrapper often decrease the cost of maintenance. If you deprecate it:
- (_more work now_) you need to change more stuff in this PR and bother about deprecation warnings;
- (_more work in the future_) you need another commit to actually remove this function; if you decide to change how you get the terminal size in the future, you'll need to change all the places where shutil was used rather than just one place: `click.get_terminal_size`;
- a minor backward incompatibility.

I only see overhead for no tangible advantage. That's why I asked. It's not my intention to start a debate about it... I don't care about `click.get_terminal_size`.
