### ISSUE TITLE
Will _unicodefun._verify_python3_env be removed in v8.0.0?

### ISSUE THREAD

**Issue by GFleishman** [pallets/click#1751]
Hi all,

Not sure why, but pip grabbed v8.0.0a1 (pre-release) from PyPI as a dependency for another package. That package is using _unicodefun._verify_python3_env - which seems to be removed from v8.0.0a1. Reverting to version 7.1.2 fixed the problem for me for now, but will this function not be present in v8.0.0a1 - or maybe it has been moved?

Thanks!

**Comment by davidism** [comment]
If you pulled 8.0.0a1 without asking, you have a *very* old version of pip and you should upgrade, or you used easy_install and you should use pip.

The function you're referring to is still present, I'm not sure why you're seeing otherwise. I just confirmed it's importable with 8.0.0a1 installed. That said, you should never be interacting with that module or function directly, it's marked internal.
