### ISSUE TITLE
Completion: Multiple sections

### ISSUE THREAD

**Issue by zachriggle** [pallets/click#1762]
It would be nice if the Click completions supported multiple sections, so that they can be rendered.  

ZSH has support for this, and I know the default `ssh` completion does this by default, if you want to play with it.

```
$ ssh <tab>
 -- domain --
Zach-Riggles-iMac.local     Zachs-Mac-Mini.local    amateria.smashthestack.org   kubernetes.docker.internal
 -- host --
ctf                              hostname2
 -- login name --
off
```

**Comment by davidism** [comment]
This will be *possible* to implement in 8.0 with the new completion system, however I'm leaving it up to click-completion or some new extension to provide such behavior. You'd need to return extra metadata on the `CompletionItem` objects returned by the relevant `shell_complete` methods, output that extra information in `ShellComplete.format_completion`, then provide a more complex ZSH script that handles that extra metadata. The problem is that these sorts of extended behaviors get very specific to the tool, while Click is a general framework.
