### ISSUE TITLE
python type hints and well defined parameters for decorators

### ISSUE THREAD

**Issue by aucampia** [pallets/click#1764]
I would like to have well defined types and type hints for click so that click is easier and safer to use.

Having this would make it possible to detect some classes of click usage errors with a python type checker like mypy. This problem could be solved by wrapping Click, but I would prefer to just add the type checking in click itself.

I am working on a patch to add type hints, I'm opening this issue so I can gauge what would be acceptable for you so I don't do something that you won't accept.

My plan more or less is:
 1. enable mypy checking from your pre-commit hook for all files in src with this config:
  ```ini
[mypy]                                                                                   
python_version = 3.6                                                                     
warn_unused_configs = true                                                               
ignore_missing_imports = true                                                            
disallow_untyped_defs = true                                                             
warn_redundant_casts = true                                                              
warn_unused_ignores = true                                                               
warn_no_return = false                                                                   
  ```
 2. Add type hinting so mypy completes without errors
 3. Add well defined parameters for decorators (I will likely use type overload so that you can still pass arbitrary parameters if you use custom classes) so that auto completion and type checking works properly for decorators

**Comment by davidism** [comment]
See [Werkzeug](https://github.com/pallets/werkzeug/) and https://github.com/pallets/werkzeug/pull/1995 for how I applied typing to Werkzeug.

Things to look at:

* Config in `setup.cfg`, what is enabled/ignored for now
* Use `import typing as t` instead of importing a ton of names into each module to avoid polluting the namespace.
* Avoid importing Click objects between modules, use `if t.TYPE_CHECKING` as a guard. This avoids circular imports and polluting the namespace.
* Don't use `typing_extensions`, quote things that aren't available in Python 3.6.
* When using `overload`, do `import typing` in addition to `import typing as t` then use `typing.overload`, to avoid a shortcoming in pyflakes/flake8.

MyPy is way too annoying to use during pre-commit, so don't do that.
