### ISSUE TITLE
Use `col_max` for `format_commands`

### ISSUE THREAD

**Issue by MarcelRobitaille** [pallets/click#1842]
Actually use `HelpFormatter.write_dl`'s `col_max` when generating usage. I have a lot of commands with long names, and I don't want the description of these to come on the following line, when simply adding some characters to the column with of the command name would make everything look very nice.

Before would be like:
```
short-command                      Docstring for short command
very-very-enormously-long-command-name
                                   Docstring for long command
```

And after bumping `col_max` a bit above 30:
```
short-command                           Docstring for short command
very-very-enormously-long-command-name  Docstring for long command
```

I am opening a pull request for this as well.

**Comment by janLuke** [comment]
This is just the nth instance of a larger problem (#561). 

In Click 8, you can solve your problem using the class attribute `Context.formatter_class`. The name of this attribute is unfortunate because it suggests a class is needed, but actually all it's needed is a callable that returns a formatter. The fact that it is a class attribute is quite bad as well.

```python
def make_formatter(width, max_width):
    return HelpFormatter(width=width, max_width=max_width, col_max=40)

Context.formatter_class = make_formatter
```

Of course your context attribute is nicer but you could add similar attributes for `index_increment` and many other possible formatting settings. 

IMHO, all these formatting options shouldn't clutter the context. This is what I'd do:
- make `HelpFormatter` stateless
- remove formatting options like `terminal_width`, `max_content_width`; they belong to the formatter
- `Context` should have an attribute `formatter` to set a default formatter that propagates to children
- `Command` should have an attribute `formatter` to override the default of a specific command (without propagating to children).

So you would do:
```python
@group(context_settings={
    'formatter': HelpFormatter(col_max=40, ...)   # set your custom global default 
})
def root():
    pass

@command(formatter=HelpFormatter(col_max=30, ...))   # override for a single command
def subcommand():
    pass
```

Now:
- `Context` is leaner and has a responsibility less (creating the formatter).
- A custom `HelpFormatter` subclass can have arbitrary settings that can easily be set globally without the need for factory functions and even for a specific command (without propagating the formatter), which is currently not possible.
- the formatter is now a dependency of `Command` as it should be, not a clunky class attribute of `Context`; both `Command` and `Context` are more testable.
