### ISSUE TITLE
Why.rst documentation

### ISSUE THREAD

**Issue by guifelix** [pallets/click#1854]
Lists are inconsistent & ``argparse`` is mentioned inconsistently 

Creating this issue as suggested when opening a PR

**Comment by ThiefMaster** [comment]
> Creating this issue as suggested when opening a PR

I don't think it makes much sense to open an issue for a minor documentation issue when you already have a PR.

Assuming it's about this message in the template, this is more about the development of features or other larger code contributions - it sucks for everyone if someone spends a lot of time to implement some feature, and then it gets rejected because it doesn't belong upstream for example.

> Before opening a PR, open a ticket describing the issue or feature the
> PR will address. Follow the steps in CONTRIBUTING.rst.

But clearly that's not the case for a documentation fix and similarly small improvements ;)
