### ISSUE TITLE
Allow to access params by name in order to simplify validation

### ISSUE THREAD

**Issue by memeplex** [pallets/click#1920]
Sometimes I end up with code like this:

```python
    if not input.endswith(".ipynb"):
        raise click.BadParameter("Unsupported file type", param=cli.params[0])
```

which is convenient because I don't have to define callbacks for such a simple task (callbacks clutter the module global scope and have more boilerplate). But having to access to the param positionally is not very cool, specially when there are many params. And `param_hint` is not quite the same, I prefer to depend on standard click behavior whenever possible.

**Comment by janLuke** [comment]
You can easily solve with a one-liner
```python
params_by_name = {param.name: param for param in cli.params}
```
but I agree that this is a nice-to-have. In fact, I personally needed this in [Cloup](https://github.com/janLuke/cloup) to implement "constraints", so I had to add a method `get_param_by_name`. Not a big deal but it wouldn't hurt if it was already in Click.

**Comment by memeplex** [comment]
I tend to do `next(p for p in cli.params if p == "name")` instead because it would be quite unusual that I needed another one, but yeah, I meant for it to be part of the API.

**Comment by davidism** [comment]
The problem is that `command.params` only represents the params defined on the command, not necessarily the commands that are available during processing. For example, `param` does not contain the `--help` option, it's added in `get_params`, which can also and or modify parameters dynamically based on env vars, plugins, parent commands, etc. This might not be _common_, but it's a feature of Click so Click would need to support it as generically as possible. `get_params` requires the current context. So we're not really saving any typing at this point, since you now have to pass the context around.

```python
@click.command()
@click.pass_context
@click.option("--input", type=click.Path)
def cli(ctx, input):
    if not input.endswith(".ipynb"):
        raise click.BadParameter("Unsupported file type", param=cli.get_param_by_name(ctx, "input"))
```

The `param` argument to `BadParameter` isn't required, it's used to add the option names to the error message. But you can pass `param_hint` instead to get the same effect manually, since you're already processing manually.

```python
raise BadParameter("Unsupported file type", param_hint="--input")
```
