### ISSUE TITLE
Docs for version 5 suggest version 7 as the latest (while version 8 is the latest)

### ISSUE THREAD

**Issue by ivanovmg** [pallets/click#2026]
Docs for version 5 suggest version 7 as the latest one.
When clicking on the link pointing to version 7 docs, another redirect to version 8 is recommended.

Repro steps:

- Start here: https://click.palletsprojects.com/en/5.x/commands/
- Go by the link on top "Warning: This is an old version. The latest stable version is Version 7.x."
- Observe another recommendation to go to version 8 docs.

Expected behavior:
Docs for version 5 should recommend one to go to version 8 docs.

Environment:

- Python version: N/A
- Click version: N/A

![image](https://user-images.githubusercontent.com/41443370/127894161-6e52dbda-cd57-4828-aec4-de38f4909a2b.png)

**Comment by jab** [comment]
Thanks for reporting, but I don’t think it would be practical to fix this, unfortunately, so I’m closing this. We may reopen this if this turns out to be worth doing.

**Comment by davidism** [comment]
Currently, it is generated when we build the docs, so we would have to rebuild every version to update the link, which isn't practical right now. I would like to see if RTD provides a live API for fetching available versions, and make the notice check using JavaScript instead of baked into the build. That would happen in the Pallets-Sphinx-Themes repo and could start by asking RTD people if such an API exists.
