### ISSUE TITLE
pre-generated completions

### ISSUE THREAD

**Issue by max-sixty** [pallets/click#2126]
I wanted to float an idea for a feature or small library and see whether there was some reason it wouldn't be possible. 

The recent Click completions rewrite is great. But in libraries with long import times, it's fairly slow, because the library needs to be imported and queried for completions on each completion. e.g. we have a repo which has quite a few dependencies, and the import time is around 2000ms, which makes it very slow for completions. 

> and I don't think we're doing anything particularly bad — running https://github.com/nschloe/tuna shows the libraries you'd expect — though let me know if this sounds outside of expectations

I saw https://github.com/sdispater/cleo with interest — this creates a script which contains the full definitions of what to complete. The advantage is responding to a request for a completion doesn't involve running any python — it's all materialized in the shell script. The disadvantage is that it doesn't update when the library changes, until the script is regenerated.

Given the 2000ms lag, I'd strongly prefer the cleo approach. Is there some reason it wouldn't be possible to do this with click? I only have a very basic understanding of how completions work, so might be missing something.

If it is possible, I'd like to try and write something (though my hit rate of idea->implementation is not that high, so we'll see...).

Thanks in advance!

**Comment by max-sixty** [comment]
Possibly one approach would be to combine https://github.com/click-contrib/click-man with https://github.com/fish-shell/fish-shell/blob/master/share/tools/create_manpage_completions.py.

I can't seem to get it working yet (I get options completed, but not subcommands), but I'm sure it's possible.

**Comment by davidism** [comment]
> Is there some reason it wouldn't be possible to do this with click? I only have a very basic understanding of how completions work, so might be missing something.

Click is *very* dynamic, and this includes the completion system. Most data comes from methods that can be overridden, to fetch the available options, subcommands, and potentially the completions themselves. I'm not a shell developer, so I have very very limited experience with even the simple Bash/Zsh/Fish code required to enable the shell completions right now. I would not know how to write a more complex script, and I'm not clear that it would be possible for Click to support it in a general way.

That said, you're welcome to work on a library that introspects a Click application and generates a script, possibly with more stated constraints than what Click in general would have to support. If you want to research how this might be accomplished, I'm happy to answer questions on the Click channel of our Discord server https://discord.gg/pallets. If it turns out you can propose a design that would work with Click in general, I'm happy to consider a more detailed proposal then. Personally, I don't need this type of completion, so I won't have the resources to devote to designing and implementing such a system.

For your specific issue of long startup times, I'd investigate reducing that first. For example, move your imports or other startup costs such as loading data to inside the command function instead of global. You can look at `context.resilient_parsing`, which will be true when evaluating completions, to avoid expensive loads.
