### ISSUE TITLE
Add default to `click.Choice`

### ISSUE THREAD

**Issue by matan1008** [pallets/click#2137]
Hey!
I want to have a `--color` option to my program output, that will optionally receive a parameter. More generally I am trying to add a default to choice, so when specifying the option without any of the choices, a default value will be selected.

I would really like the feature to look like

```python
@click.command()
@click.option('--color', type=click.Choice(['always', 'auto', 'never'], default='always'), default='never')
def my_command(color):
    print(color)
```

So the following output will be received:

```shell
>>> python my_command.py
never
>>> python my_command.py --color
always
>>> python my_command.py --color auto
auto
```

**Comment by jcrotts** [comment]
Thanks for opening the issue. I think the proposed use case is fairly unusual so we probably won't add this to click. 

You could implement this by modifying clicks option parser or by doing some parsing on your own before calling your click application.

You could also use a feature flag to get something similar
```python
@click.command()
@click.option('--always', 'color', flag_value='always', )
@click.option('--never', 'color', flag_value='never', default=True)
@click.option('--auto', 'color', flag_value='auto')
def my_command(color):
    print(color)
```

**Comment by matan1008** [comment]
Thanks for the response!

In my humble opinion the concept of default if omitted is pretty common - even basic linux commands like `ls` and `cp` does that, as you can see in the manual https://man7.org/linux/man-pages/man1/ls.1.html (look at the `--color`).

I would really appreciate it if you reconsider the decision not to add it to click.

**Comment by jcrotts** [comment]
This works in click and I think mirrors the behavior of `--color` in ls, except passing `--color` with no argument will cause click to throw an error, where it doesn't with ls.
```python
@click.command()
@click.option('--color', type=click.Choice(['always', 'auto', 'never']), default='always')
def my_command(color):
    print(color)
```
I believe this behavior is intentional for now.
See David's comment here:  https://github.com/pallets/click/pull/1618#issuecomment-670953295

The PR where this was made explicit (see the `_flag_needs_value` variable)
https://github.com/pallets/click/pull/1618/files

PRs are always welcome if you have an implementation in mind.
