### ISSUE TITLE
Bash completion does not support bash versions older than 4.4

### ISSUE THREAD

**Issue by sirosen** [pallets/click#2152]
I maintain a CLI tool built on `click` and just had a user report issues with completion on bash 4.2 on a CentOS box.

It seems that `nosort` was added as an option in bash 4.4. There's even a comment in the completer source about this.
I think it would make sense for the completer to check for `BASH_VERSION` showing a value below 4.4 and not use `nosort` in that case. If `BASH_VERSION` is not set, it's probably safe to assume that `nosort` is permissible -- I'd rather not degrade environments with a modern bash version but which (for whatever reason) are not showing that env var.

I'm okay with `click` closing this as a wontfix (old version, not supported), but I want to document the issue and discuss the workaround. If I were to work out the necessary code for this, would there be an appetite for reviewing and merging it?

**Comment by davidism** [comment]
That's explicitly checked for, but only in order to show an error about the lack of support: https://github.com/pallets/click/blob/main/src/click/shell_completion.py#L302

This was a deliberate decision to drop older versions of Bash. Since the completion system is extensible now, if there is a need to support completion for other shells or versions, an extension can provide that.

**Comment by sirosen** [comment]
Okay, make sense. Thanks for the explanation!

At some point in the past, we had custom completion because of some issue (don't recall what) with the builtin completer. I think we're still not loading up completion in a normal way, so we're accidentally bypassing that check.
