### ISSUE TITLE
Add Bash completion support fot bash versions older than 4.4

### ISSUE THREAD

**Issue by coreegor** [pallets/click#2200]
Hi guys, 
I wanted to know why support for Bash version older than 4.4 was deliberately removed?
I think there are a lot of people who use older versions of the Bash and when they start getting familiar with Click they find autocompletions don't work out of the box. Despite having an extensible completions system, newbies to Click may decide to leave the package rather than write their own extension. It pushes new people away from using Click.

Maybe you should abandon the version check and return to choosing an option in the [shell script](https://github.com/pallets/click/blob/43e40c05a4b94c6aa497dc7bba62b7d69b7e35ec/src/click/_bashcomplete.py#L29) ?

Alternatively, maybe it's worth adding a small package to the click-contrib that would patch the original BashComplete ?
I can do it if needed.

**Comment by ThiefMaster** [comment]
People shouldn't use ancient versions... but since CentOS 7 (which is still popular on servers and not EOL for another two years) seems to come with 4.2 maybe it indeed makes sense  to keep supporting it

**Comment by davidism** [comment]
Frankly, I just don't consider the situation as dire as your phrase "newbies to Click may decide to leave the package rather than write their own extension" implies. If you're stuck using CentOS 7, sorry, but I just don't think "has completion" is a decider to abandon an entire project.

You're welcome to make an extension for it. Click-Completion already exists and would be a good place for this, but maintenance activity on it has been quiet.

**Comment by coreegor** [comment]
> I just don't think "has completion" is a decider to abandon an entire project.

In my opinion, autocomplete is one of the important features of the Сlick.

> I barely understand Bash completion enough to get working as-is.

The whole question in this case is only in using the `nosort `option

**Comment by davidism** [comment]
Yes, completion is an important feature. No, it's not the main reason for Click to exist, or for most users to choose Click.

Yes it's "only" that in this case. But whose to say we don't add another feature to completion, then need to figure out how to make that compatible as well? What if it turns out Bash 3 doesn't work, and users ask for that since we're already adding compatibility. As a maintainer with limited resources, I don't want to add more work to benefit a group of people that should be steadily decreasing anyway.

**Comment by coreegor** [comment]
@untitaker,
I've created a repo https://github.com/coreegor/click-bash4.2-completion, could I put it under click-contrib?

**Comment by davidism** [comment]
Would you be ok moving it to pallets-eco? We're slowly trying to introduce it as the place to consolidate community-maintained projects for all of Pallets.

**Comment by coreegor** [comment]
Yes, i would

**Comment by davidism** [comment]
I've invited you to the org, you should be able to move after accepting.

**Comment by coreegor** [comment]
It's done. Thanks!
