### ISSUE TITLE
Sign up for GitHub Sponsors

### ISSUE THREAD

**Issue by zachriggle** [pallets/click#2213]
I know there is already a Donate link that goes through `psfmember.com`, but it would be really great to donate through GitHub.

# Why not psfmember?

The current psfmember website requires PayPal (a company I do not do business with) or a personal check (which I don't want to use, and makes it hard to do recurring payments).

I really don't want to comment on how bat the UI / UX on that website is, but it is... not ideal.

# GitHub Sponsors

GitHub already has my payment method, and it makes it VERY easy to set up single-time or recurring payments.  It's super seamless, and there are no transaction fees unless the entity making the donation is a business.  It takes about 5 minutes total to sign up.

https://github.com/sponsors is all you need

## Additional Resources

There's a LOT more information on customization available here:
* [Announcing GitHub Sponsors: a new way to contribute to open source | The GitHub Blog](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/)
* [Getting started with GitHub Sponsors | The GitHub Blog](https://github.blog/2020-03-24-getting-started-with-github-sponsors/)
* [FAQ with the GitHub Sponsors team | The GitHub Blog](https://github.blog/2019-06-12-faq-with-the-github-sponsors-team/)
* [New sponsors-only repositories, custom amounts, and more  | The GitHub Blog](https://github.blog/2022-02-02-new-sponsors-only-repositories-custom-amounts-and-more/)

## Sponsorship Made Easy

It's ridiculously simple.  GitHub already has your payment info, 0% fees for non-companies, and it takes exactly 3 clicks to donate.  You don't need to enter ANY data other than how much you want to donate, one-time or recurring, and that's all.

If you set up Sponsors for the Organization (`pallets`) you can configure whether your sponsors show up on the right side of the Github landing page.

### Exactly Two Screenshots

It's really this easy for people to donate, AND it shows up in a standard, expected place on your repos!

<hr />

<img width="999" alt="Screen Shot 2022-03-11 at 5 15 04 AM" src="https://user-images.githubusercontent.com/111640/157857220-dada0a77-a071-4542-98eb-0b8787d71359.png">

<hr />

<img width="1019" alt="Screen Shot 2022-03-11 at 5 15 24 AM" src="https://user-images.githubusercontent.com/111640/157857273-b300fcaa-86f7-4cb4-9ff6-a81c965e7a6c.png">

**Comment by davidism** [comment]
Hi, I'm well aware of what GitHub Sponsors is, no need to make a marketing post, especially one that's geared towards an individual rather than an organization.

Pallets is a member of the PSF, and so our accounts are managed by them, and we take donations through them. Other funding sources, such as Tidelift and Read the Docs, have worked out with the PSF how to get money to them directly. While it seems like there may be a way to connect a PSF account with GitHub, it is not something I've had time to investigate yet, given everything else I am responsible for.

I'm not sure I understand the "bad UI" objection. It seems to have the same behavior as the GitHub page: enter your information, select your payment method, select the amount, and click donate. I haven't been confused or had any issues using it in the past. Perhaps you're referring to the website's design instead? Either way, that's something you'll need to take up with them.

See https://www.python.org/psf/donations/ for other ways to donate. The PSF can accommodate other payment methods, such as Zelle transfers. Contact them at psf-donations@python.org for assistance.

I'm going to close this, as I don't need an issue to track it. I am aware of GitHub Sponsors and may enable it in the future if I have time to do so.

**Comment by davidism** [comment]
I sent a message to our PSF financial contact, but I can't say whether it will be easy or quick to set up.
