### ISSUE TITLE
Callback on options fires twice

### ISSUE THREAD

**Issue by Elysium1436** [pallets/click#2259]
Minimum code to reproduce:
```python
from pprint import pprint

import click


def handler(ctx, param, value):
    ctx.obj = {}
    print("handler has been fired")
    match value:
        case "time":
            input_value = click.prompt("Select input for time", type=str)
            ctx.obj["input_value"] = input_value
        case "quantity":
            input_value = click.prompt("Select input for quantity", stype=int)
            ctx.obj["input_value"] = input_value
    return value


@click.group()
def cli():
    return


@cli.command()
@click.option(
    "--an-option",
    prompt=True,
    type=click.Choice(["time", "quantity"]),
    callback=handler,
)
@click.pass_context
def test_command(ctx, **kwargs):
    pprint(ctx.obj)
    pprint(kwargs)


if __name__ == "__main__":
    cli()
```
output
```
python cli.py test-command
An option (time, quantity): time
handler has been fired
Select input for time: 10
handler has been fired
Select input for time: 10
{'input_value': '10'}
{'an_option': 'time'}
```
We can see that the message "handler has been fired" shows up twice.

**Comment by davidism** [comment]
This is due to how the processing pipeline works. Since the value wasn't given, it's prompted for. The prompt calls the callback to ensure the user typed a valid value before continuing. Then the value continues through the processing pipeline, which calls the callback (regardless of source) to validate the option before passing it to the command.

You can check if `input_value` has already been stored in the context object before doing your additional prompting.

**Comment by Elysium1436** [comment]
I see, much thanks for the thorough explanation! That being said, why does the prompt get passed the same callback that's already being used by the main command? Wouldn't this mean that the same value is being redundantly validated an extra time?
