### ISSUE TITLE
Automatically create directory if it doesn't exists

### ISSUE THREAD

**Issue by dedalusj** [pallets/click#226]
Sometimes CLI scripts requires destination directories or similar as argument or options.

I know this could easily be achieved otherwise but it would be handy to have an option to let click automatically create such directory if it doesn't exists.

**Comment by trombonehero** [comment]
I was just about to open a similar issue... could this decision be revisited? For programs that produce output, I'd like to be able to write something like:

```python
@click.option('-o', '--output', type=click.File('w', mkdir=True),
              default='results/foo.txt', help='Destination file')
```

so that I can use `click.File`'s automatic file-or-stdout facility. Otherwise I need to use `click.Path` and do my own `os.makedirs()`, `open()`, etc.
