### ISSUE TITLE
--help --version should stop completion

### ISSUE THREAD

**Issue by Freed-Wu** [pallets/click#2343]
Environment:

- Python version: 3.10.5
- Click version: 8.1.3

<https://github.com/psf/black/issues/1576#issuecomment-1228801355>

Expected behaviour:

```
❯ black --help <TAB>
no more arguments
```

Actual:

```
❯ black --help --<TAB>
unsorted
--code                        Format the code passed in as a string.
--line-length                 How many characters per line to allow.
--target-version              Python versions that should be supported by Black's output. [default: per-file auto-detection]
--pyi                         Format all input files like typing stubs regardless of file extension (useful when piping source on standard input).
```

**Comment by davidism** [comment]
This is not possible due to the very dynamic nature of Click. `--help` and `--version` aren't fixed names, and any callback, not just those two, could potentially terminate processing early. The parser (and completer) only know about the tokens, not what those tokens might do.

There's nothing inherently wrong about typing more things after an option that ends processing. This is not something I plan to address.
