### ISSUE TITLE
group with argument with nargs=-1 fails to dispatch to sub-commands

### ISSUE THREAD

**Issue by pjz** [pallets/click#2384]
a `click.group()` that has a `click.argument()` with `nargs=-1` fails to dispatch to sub-commands.

if we have mycmd.py:
```python
import click

@click.group()
@click.argument('files', type=click.Path(), nargs=-1)
def cli(files):
    print(f'files: {files!r}')

@cli.command()
def get():
   print("subcommand 'get'")

if __name__ == '__main__':
    cli()
```
running something like `mycmd.py somefile get` results in:

```
Error: Invalid value for 'FILES...': File 'get' does not exist.
```
Where it should obviously instead do:
```
files: somefile
subcommand 'get'
```

Environment:

- Python version: 3.9.2
- Click version: 8.1.3

**Comment by maxwthomas** [comment]
I'm going to take a crack at this during PyCon 2024 sprints

**Comment by maxwthomas** [comment]
I was able to replicate the issue, but I believe this is an intentional design of the library. The root of this issues starts in [parse_args](https://github.com/pallets/click/blob/8.1.2/src/click/core.py#L1608) in the `MultiCommand` class:
```python
    def parse_args(self, ctx: Context, args: t.List[str]) -> t.List[str]:
        if not args and self.no_args_is_help and not ctx.resilient_parsing:
            echo(ctx.get_help(), color=ctx.color)
            ctx.exit()

        rest = super().parse_args(ctx, args)

        if self.chain:
            ctx.protected_args = rest
            ctx.args = []
        elif rest:
            ctx.protected_args, ctx.args = rest[:1], rest[1:]

        return ctx.args
```
Which invokes [parse_args](https://github.com/pallets/click/blob/8.1.2/src/click/core.py#L1369) in the `Command` class to parse the initial command.

In theory, what should be returned from the call to `parse_args` in the `Command` class is the rest of the arguments not handled by the command, which in the case of subcommands, should be the subcommand and its remaining arguments. 

If I change the example above to limit the amount of `files` args to 1, but still run something like `mycmd.py test.file get` I see this works as expected:
![image](https://github.com/pallets/click/assets/49256746/8864d534-25d0-40c1-b32c-de53206a6f52)
And I get the desired output:
![image](https://github.com/pallets/click/assets/49256746/941aaa22-b5dc-45fc-8339-e36006f6d98d)

But, if I change the example back to the number of `files` args to `nargs=-1`, there are no `rest` arguments returned, i.e. the command swallowed up all of the arguments, which should've been used for the subcommand:
![image](https://github.com/pallets/click/assets/49256746/961c7714-02f6-48b4-8718-d284f45d77d5)

However, I believe this is intended by the developers. From the [docs](https://click.palletsprojects.com/en/8.1.x/arguments/#variadic-arguments) on using `nargs=-1`:
> Note that only one argument can be set to nargs=-1, as it will eat up all arguments.

And we see that as expected in this example, it is eating up all of the arguments, it's just unfortunate that one of those arguments is the subcommand. The [docs](https://click.palletsprojects.com/en/8.1.x/commands/#multi-command-chaining) are also clear when using `chain=True` on the call to `@click.group()` to do > 1 subcommand about using this `nargs=-1`:
> When using multi command chaining you can only have one command (the last) use nargs=-1 on an argument.

I believe that this case of a single subcommand not using `chain=True` fell through the cracks of the docs but is intended not to be able to handle `nargs=-1` in the command. It would be nice if an exception would be thrown similar to using `nargs=-1` on not the last chained subcommand as well.
