### ISSUE TITLE
escape characters \b \f make "invalid escape sequence" warning

### ISSUE THREAD

**Issue by Solvero** [pallets/click#2393]
Click formatting escape characters (\b \f) generate *mypy* warning:

DeprecationWarning: invalid escape sequence

They are documented here:
https://click.palletsprojects.com/en/8.1.x/documentation/#preventing-rewrapping
https://click.palletsprojects.com/en/8.1.x/documentation/#truncating-help-texts

Many pages  (https://www.flake8rules.com/rules/W605.html) suggests to use raw string to get rid of warning 
but then "preventing rewrapping" doesn't work.

Environment:

- Python version: 3.10.6
- Click version: 8.1.3

**Comment by davidism** [comment]
We need to come up with new syntax for these two markers. The nice thing about the escapes is that they would never appear in actual help text. Anything else we come up with, a user might conceivably want to actually output in the help text itself.

This falls in the general "extensible formatter" category of feature requests, so we also want to think about how other formatters might handle this once we have that capability.

@willmcgugan any suggestions based on how rich does things? We want to be able to mark a paragraph as "don't re-flow these lines", and mark a "below the fold" line so that extra help can show in Python but not in the CLI.

**Comment by davidism** [comment]
I guess we could look for the two-character sequence `\b`, which would either be written `"\\b"` or `r"\b"`, rather than the special character.

**Comment by Solvero** [comment]
This sounds OK for me.

**Comment by davidism** [comment]
Both `\b` and `\f` do not show a warning, and are valid according to https://docs.python.org/3/reference/lexical_analysis.html#strings.

**Comment by Solvero** [comment]
Agree. Something has changed, and mypy doesn't report it anymore.
