### ISSUE TITLE
make_pass_decorator mechanism works with dict, but not list?

### ISSUE THREAD

**Issue by ZacharyACoon** [pallets/click#2411]
### Summary

pass_dict_context = `click.make_pass_decorator(dict)` mechanism seems to pass the same object.
pass_list_context = `click.make_pass_decorator(list)` mechanism seems to pass a different object.

I think it's related to this: https://github.com/pallets/click/blob/main/src/click/core.py#L620-L639

### Test Code
```python
import click

pass_dict_context = click.make_pass_decorator(dict, ensure=True)
pass_list_context = click.make_pass_decorator(list, ensure=True)


@click.group(chain=True)
# decorators wind up running in reverse
@pass_list_context
@pass_dict_context
def cli(test_dict, test_list):
    pass


@cli.command()
@pass_list_context
@pass_dict_context
def add_data(test_dict, test_list):
    test_dict["abc"] = 123
    print("add_data, test_dict", id(test_dict))
    test_list.append("123")
    print("add_data, test_list", id(test_list))
    print()


@cli.command()
@pass_list_context
@pass_dict_context
def show_data(test_dict, test_list):
    print("show_data, test_dict", id(test_dict))
    print("show_data, test_list", id(test_list))
    print()
    print(test_dict)
    print(test_list)


if __name__ == "__main__":
    cli()
```

### Output
```
add_data, test_dict 139840449413248
add_data, test_list 139840449413952

show_data, test_dict 139840449413248
show_data, test_list 139840449414080

{'abc': 123}
[]
```

Environment:

- Python version: 3.10.8
- Click version: 8.1.3

**Comment by davidism** [comment]
The main issue is that you can't have multiple pass decorators, they just overwrite each other. First you're ensuring there's a list, then you're _ensuring_ there's a dict, so `ctx.obj` becomes a dict.

You've added confusion to the example by using chained subcommands. The `cli` command ensures a list, then a dict overwriting the list. Then the `add_data` command ensures a list on the child context, then ensures a dict which finds the parent dict. Then the `show_data` does the same thing. So ultimately, the dict set by the parent is seen when it's asked for, but the list is specific to each context because the parent is a dict, not a list.

Ultimately, `ctx.obj` can only be one thing. Trying to ensure it's multiple things can't work.
