### ISSUE TITLE
Request for general mechanism to support long command lines that overflow platform max length

### ISSUE THREAD

**Issue by mkillianey** [pallets/click#2427]
I am currently using Python's `argparse` for an application that I would like to convert to use Click.  The application's argument list can get _very_ long, so it uses [`fromfile_prefix_chars`](https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars) to support reading arguments from a file.

This is a request for one of:
(1) A comparable feature -- to support a prefix that reads args from a text file.
(2) A cookbook for alternative strategies.  As an example, `git add --pathspec-from-file=<file>` solves the problem of `git add` receiving too many pathspecs, but adds complexity to the code that must combine arguments from both places.  Is there a neat solution that doesn't involve adding a new flag?
(3) If this is an anti-pattern that Click doesn't want to support, then perhaps a few lines in a design doc somewhere that explicitly discusses this.

If Click already supports this and I've missed it in the documentation, could you perhaps add a comment that explicitly mentions `fromfile_prefix_chars` to make it easier for the next person doing an `argparse`-to-`click` conversion to find?

Thank you!

**Comment by davidism** [comment]
Click's goal is not to implement every feature of every other CLI library or tool. This sounds like something that could be done with an extension without requiring any Click-specific changes.

I don't plan to add more documentation about this, since documenting everything we _don't_ support is unsustainable.

**Comment by gpxricky** [comment]
@davidism I would kindly ask you to reopen this issue for further discussion on that topic.

You are totally right. Implementing a feature, just because an alternative solution like argparse has it, isn't the right approach. However, from my point of view there is a high need for this feature and it would make sense to have it built in into Click. I would go even further to say that every Windows user has the potential need to use this feature. 

Unfortunately Windows has a limit for command line input at 8191 characters (https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation). This sounds very much at the first moment. However, people like @mkillianey and me are struggling with it. Why is this the case? Usually this happens if your application supports command line options that may occur multiple times and accept a path. Imagine a C compiler that supports adding include paths or defines via command line (which is usually the case). Such applications usually have a mechanism to provide at least some of the options as file. On Windows the most popular solution I know so far is a command line option like `@input_file`.

I haven't checked the past, but it may also an indication for the need of this feature that this question has asked two times in one week ([here](https://github.com/pallets/click/issues/2427) and [here](https://stackoverflow.com/questions/75085299/any-fromfile-prefix-chars-equivalent-for-python-click)).

This is just to provide you some more details on the topic. At the end it is up to you to implement it or not.

Anyway, developers like @mkillianey and me need a solution that works with the current version of Click. I would like to start implementing an extension, but to be honest I don't know where to put my hands on.

I would imagine that a solution could look like the below one:

- Before evaluation of the command line arguments by Click, I would like to walk through sys.argv and replace all "@file" items with the content of that file
- Each line in the file shall be a single argument that is provided to sys.argv
- The result shall be handed over to Click which does its regular evaluation

I know that people usually suggest to use eager options with a callback and adjust the default map. However, that doesn't work exactly the way I was looking for. Especially when using nested commands or arguments this is getting worser and worser and would require some internal knowledge from the user which is not acceptable for me.

Is there any other extension point I can use?

Many thanks and best regards,
Markus
