### ISSUE TITLE
Sudden Performance Break after Reinstalling Ubuntu 22.04

### ISSUE THREAD

**Issue by cap-jmk** [pallets/click#2474]
After reinstalling Ubuntu 22.04 from scratch, there were sudden performance breaks. The cli is not streaming the output of commands properly and only using a tiny fraction of available cores. My test took less than 7 minutes prior to the reinstall. Now, it takes over 20 minutes. It is not much of a problem now, but may later become a big headeache when running on high performance applications. 

## Replicate 

Clone carate [repo](https://codeberg.org/sail.black/carate.git)

Run 
```bash
[git clone](https://codeberg.org/sail.black/carate.git)
git checkout dev
pip install -e . 
pytest tests/
```

Environment:

- Python version:
- Click version:

**Comment by ThiefMaster** [comment]
I think you need to do a bit of debugging yourself here and ideally reproduce it in a minimal example... but 7 min vs 20 min sounds like something that is almost certainly NOT related to click but rather something in your application logic or environment being the bottleneck (e.g. missing binary speedups and falling back to pure python code - something that could be caused by the lack of a python-dev package or not having a compiler installed).
