### ISSUE TITLE
README.rst: Weird characters in heading

### ISSUE THREAD

**Issue by gregorni** [pallets/click#2611]
In the project README, the heading reads `$ click_`. Are those dollar-sign and underscore there on purpose?

**Comment by ThiefMaster** [comment]
Yes. Already like this since the very first version of the [README](https://github.com/pallets/click/blob/61494320c58f1f24612183e281d5cc11ac12d44e/README).

I think the `$` stands for the typical shell prompt (even though most people use something much more fancy nowadays); no idea what the `_` at the end stands for though...
