### ISSUE TITLE
Request to document some basic features explicitly

### ISSUE THREAD

**Issue by joe-saronic** [pallets/click#2693]
1. If I type hint functions decorated by `click.command`, the argument type is typically easy to determine/guess. Would it be possible to add the recommended type hint for `click.File` objects in the docs? For example:
   ```
   @click.command()
   @click.argument(
        "input",
        type=click.File("rt", encoding='utf-8'),
   )
   def myfunc(input: <what goes here?>) -> None: ...
   ```
2. I don't see an explicit mention in the docs of how options and arguments behave when combined. Should options always appear before arguments at they typically do in Unix? Do function parameters corresponding to options appear in the order of the decorators, or do they get bunched first?

**Comment by davidism** [comment]
We don't have documentation about type hints in general, because it's no different than how you'd hint normal Python. In the case of a text file, that would be `typing.IO[str]`.

Options and arguments behave normally when combined. Options usually come first visually, but it doesn't matter. They're all passed by keyword.

**Comment by joe-saronic** [comment]
Thanks for the explanation, and for maintaining such a useful package. I did not realize that parameter order is irrelevant. Now that this ticket exists, it's probably sufficient documentation.
