### ISSUE TITLE
Sanitization for click inputs

### ISSUE THREAD

**Issue by Tylerlhess** [pallets/click#457]
I would like to see some method of easy sanitation after an input. I guess I could define a type and require that type for the input but that seems a little extravagant if I want to make sure that say a field entered is a valid email address during input or to strip out spaces automatically. I know I can do this in the code but it should be possible inside prompt.

**Comment by mitsuhiko** [comment]
Can you not use our callback system for this?

**Comment by mitsuhiko** [comment]
Oh I see. We might only invoke the type conversion but not the callbacks for prompts currently.  I wonder if that can be changed though.

**Comment by piroux** [comment]
It would be a good feature indeed.

**Comment by Tylerlhess** [comment]
Yeah in the code I wrote I ended up just calling strip to sanitize it somewhat and prevent spaces at the beginning and the end but that does not actually validate the data. It does fix the issue I had of people using copy and paste and grabbing a space but not the underlying problem of allowing a complete input sanitization check.

**Comment by davidism** [comment]
`Parameter.callback` is already called for the result of `prompt` (or any other parameter source), but it's called *after* `prompt` returns, not inside it. So while it's possible to perform extra processing, if that processing raises a `click.UsageError` it exits instead of prompting again.

I'm not sure if this was always the case or if it was due to recent refactors to the type processing pipeline. I think we can extend that refactoring a bit further though to address this issue. `prompt` is passed `self.process_value`, which only does type conversion. However, `handle_parse_result` calls `full_process_value` (which calls `process_value`) then applies the callback separately. There's no reason to have that separate anymore, and along with that there's no reason to have both `process_value` and `full_process_value`.

1. Inline `Parameter.process_value` into `Parameter.full_process_value`, then rename `full_process_value` to `process_value`.
2. Move the `if self.callback:` block from `Parameter.handle_parse_result` to the bottom of `process_value`.
3. `prompt` is still passed `self.process_value`, but now that method is doing other checks as well as invoking the callback. All the checks raise `UsageError`, so they should still be handled correctly by `prompt`.

**Comment by Saif807380** [comment]
I'd like to work on this.
