### ISSUE TITLE
Sub-commands help truncation in upper-level command help.

### ISSUE THREAD

**Issue by AndrewPashkin** [pallets/click#486]
This example:

```python
import click

@click.group()
def cli():
    """Top-level spam."""
    pass

@cli.command()
def eggs():
    """Second-level spam: spam, spam, spam, spam, spam, spam! Lovely spam!
    Wonderful spam! Lovely spam! Wonderful spam!
    """
    pass

if __name__ == '__main__':
    cli()
```

used together with Click 6.2,  will produce:

```
$ python click_test.py 
Usage: clitest.py [OPTIONS] COMMAND [ARGS]...

  Top-level spam.

Options:
  --help  Show this message and exit.

Commands:
  eggs  Second-level spam: spam, spam, spam, spam,...
```

Notice ellipsis in the end and truncated help for `eggs` command - it was made by Click, not by me.

How to avoid that?

**Comment by preethi29** [comment]
Hi you can pass the help text as short_help like
`@cli.command(short_help="Second-level spam: spam, spam, spam, spam, spam, spam! Lovely spam!
    Wonderful spam! Lovely spam! Wonderful spam!")`

**Comment by L3O** [comment]
I came across the same issue. I was checking the code and if a short_help is not defined it restrict the help length to 45 characters. If it is longer than 45 it adds the ellipsis in the end and truncate the string.

Why is it defined to 45 characters ?
Also, if it has to restrict to 45 characters, wouldn't be short_help instead of help ?
It looks like the purpose of help and short_help are inverted.

**Comment by ssbarnea** [comment]
@mitsuhiko While this was closed more than 4 years ago, I cannot ask myself why it was closed without any explanation as it clearly looks like a valid bug in click.

The current behavior of click regarding `help` and `short_help` seems just wrong.
