### ISSUE TITLE
Change options header value

### ISSUE THREAD

**Issue by mbiokyle29** [pallets/click#512]
I was just wondering if there was a parameter that could be set to change the values used in the headers of the help output. For example:

Here is what I have now

```
Usage: cli [OPTIONS]

Options:
  --max-threads <int:threads>  Specify a different max # of N upload threads
                               (defaults to 4)
  --no-pretty-print            Do not pretty-print JSON responses
  --no-threads                 Do not use multiple background threads to
                               upload files
  --version                    Show the version and exit.
  -h, --help                   Show this message and exit.
```

I'd like to be able to modify the `Options:` part to something like:

```
Usage: cli [OPTIONS]

My App Options:
  --max-threads <int:threads>  Specify a different max # of N upload threads
                               (defaults to 4)
  --no-pretty-print            Do not pretty-print JSON responses
  --no-threads                 Do not use multiple background threads to
                               upload files
  --version                    Show the version and exit.
  -h, --help                   Show this message and exit.
```

Thanks!

**Comment by jcrotts** [comment]
The "Options" part of the help text is written in `format_options` [here](https://github.com/pallets/click/blob/1b1578dbbc706538914221352edc84d532cdd3a4/src/click/core.py#L1234)

If you want to change the default text you can subclass `click.Command` and override the `format_options` and or the `format_help` method.

I don't think this is something we want to parameterize, because its fairly easy to subclass.

**Comment by mbiokyle29** [comment]
@jcrotts Thanks for following up!

**Comment by jcrotts** [comment]
Thanks for opening the issue!
