### ISSUE TITLE
Support click.option with default values / optional arguments

### ISSUE THREAD

**Issue by mbrancato** [pallets/click#549]
Since the default value always applies, there should be a way to differentiate between the following options usage:

file.py
file.py --foo
file.py --foo 2

where '2' is an argument to --foo. This should produce 3 different values for the destination of 'foo'. This is implemented in argparse with nargs='?' but has no functional equivalent in click (that I can identify). I've created a pull request that implements a potential solution. I'm not asking for a specific way of implementing the solution, and what I provided is mostly for a functional example. It does need test cases.
#548

**Comment by untitaker** [comment]
How would you know if `2` is an argument to `file.py` or `--foo`?

**Comment by ZenithDK** [comment]
I had a similar issue.
I want to check that the input values are different from the defaults, and I ended up with this (in case others want the same):
```
@cli.command()
@click.option('--usb')
@click.option('--adk')
@click.pass_context
def local(ctx, usb, adk):
....
    default_dict = dict(zip([command.name for command in ctx.command.params], [command.default for command in ctx.command.params]))
```
Then you can look up the defaults in default_dict - and compare to what you received.

**Comment by anarcat** [comment]
@untitaker ordering. first comes first served.

**Comment by anarcat** [comment]
could this be merged if unit tests are added to #548? this is a feature i'm often missing from click...

is there a way to monkeypatch our way around this limitation?

**Comment by pombredanne** [comment]
The thing here is that there is no way to tell if an option was entered by a user or if the default value has been used. A user-entered option that has the same value as the default is the same as a non user-entered option with a default. As a result, the simple nargs='?' pattern in argparse cannot be implemented and instead two options must be used: a flag and a value. See https://gist.github.com/pombredanne/aeab7f5b4783919dfe5265b2c553cdb8 for some examples.

**Comment by Evidlo** [comment]
@pombredanne argparse provides a `const` option in addition to `default`.  

    add_parser = subparsers.add_parser('add')
    add_parser.add_argument('-w', '--words', metavar='length', type=int, nargs='?', const=5, default=None)

So `foo add` means `args.words == None`, `foo add -w` means `args.words == 5`

**Comment by pombredanne** [comment]
@untitaker would you like to see this in Click or not?

**Comment by mbrancato** [comment]
How does Click conform to say the POSIX command line argument syntax standard without supporting optional option-arguments?

**Comment by anarcat** [comment]
@mbrancato which POSIX standard? could you link to or quote the relevant section? oh no, you can't, because IEEE standards are [behind paywalls](https://standards.ieee.org/findstds/standard/1003.1-2017.html)... :p 

i mean i'm all for implementing this feature, but heralding POSIX here does not further the discussion..  I think the only thing that needs to happen is to complete unit tests in #548 and make sure they suffice for this issue to be fixed.

@mbrancato you wrote that code, i guess it was to resolve this issue?

how does your code resolve the following ambiguities?

```
--foo --bar
--foo 2 --bar
--foo -- 2 --bar
--foo --bar 2
``

**Comment by Evidlo** [comment]
[POSIX Utility Conventions](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)

**Comment by untitaker** [comment]
Excuse me, how does it not conform to those conventions?

**Comment by Evidlo** [comment]
Click doesn't support the `[-f [optional_argument]]` bit.

**Comment by untitaker** [comment]
Conforming to a convention does not mean that it has to fully exercise all rights. I can conform to a protocol without using all of its features

**Comment by Evidlo** [comment]
The document specifies a well defined behavior for `[-f[option_argument]]`

    If the SYNOPSIS shows an optional option-argument (as with [ -f[ option_argument]] in the example), 
    a conforming application shall place any option-argument for that option directly adjacent to the option 
    in the same argument string, without intervening <blank> characters. If the utility receives an 
    argument containing only the option, it shall behave as specified in its description for an omitted 
    option-argument; it shall not treat the next argument (if any) as the option-argument for that option.

I don't understand the resistance.

**Comment by pombredanne** [comment]
I am willing to chip in a PR. I had to create quirky option subclasses to handle this in a brittle way ;) And I options with a default that is activated only if the option is selected is a bit more than nice to have for me  (FWIW, this is how one of my more fleshed out CLI help looks like: https://github.com/nexB/scancode-toolkit/blob/develop/tests/scancode/data/help/help.txt )

**Comment by untitaker** [comment]
Click conforms because the synopsis will never show this, because click doesn't support the feature. Therefore it conforms. Your second quote does not support your argument.

The suggestions in both the guideline and in this thread to resolve the parsing ambiguity are not good UX imo. I don't really know why anybody needs this feature. Why not have two options?

**Comment by anarcat** [comment]
> I don't really know why anybody needs this feature. Why not have two options?

Here are two examples of how I use this feature with the argparse module. I have a `--syslog` flag that when specified alone, sends logs with the `INFO` level to syslog, but an optional argument can also be specified to tweak the logging level (`--syslog WARNING`). i could make a `--syslog-level` level, but that makes the whole commandline a little verbose (e.g. `--syslog --syslog-level WARNING`). Also, what happens if `--syslog-level WARNING` is specified alone? i am *guessing* that it will *not* enable the `--syslog` flag, so this is rather error prone.

another example is a `--force` flag: by default, it forces "everything" to happen, but I'd like to be able to restrict to some subsystem (e.g. `--force=metadata`).

**Comment by pombredanne** [comment]
My use cases are different but resort to the same. For instance I have plugins that contribute various output format options. If no output files is specified I would like this to default to `stdout` e.g. `-`
Today this is really hard todo even custom: how do you distinguish from a non-selected option with a default value vs. an option that was selected? (irrespective of the other discussions here, this is something rather difficult)

**Comment by Evidlo** [comment]
I have a password generator that can be used for generating symbolic (default) or word-based passwords of varying length.

With argparse, it looks like this

```
usage: ph add [-h] [-w [length]] PATH

positional arguments:
  PATH                  path to entry (e.g. 'foo') or group (e.g. 'foo/')

optional arguments:
  ...
  -h, --help            show this help message and exit
  -w [length], --words [length]
                        generate 'correct horse battery staple' style password
                        when creating entry
  ...
```

In Click, the synopsis would be a bit more cluttered and you have to code in that `length` requires `-w` (not sure if that is built in).

```
usage: ph add [-h] [-w] PATH

positional arguments:
  PATH                  path to entry (e.g. 'foo') or group (e.g. 'foo/')

optional arguments:
  ...
  -h, --help            show this help message and exit
  -w, --words
                        generate 'correct horse battery staple' style password
                        when creating entry
  --length          specify the length of a password (requires argument -w)
  ...
```

I think it would get ugly pretty fast if you had multiple of these option + optional arg pairs.

**Comment by pombredanne** [comment]
@untitaker re

> Why not have two options?

When you start to have two options for most options and have quite a few options, this is doubling the number of options and gets you an ugly UX & help very quickly, guaranteed to confuse your users together with less explicit, and more verbose code with a lot of boilerplate for no good reasons IMHO.

Now leaving aside POSIX,  the doc example is to build a git clone. This would not actually be possible with Click as it is: for instance `$ git branch --column` , `$ git clone --recurse-submodules` , `$ git init --shared` and other options such as `--log`, `--gpg-sign` , `--rebase`  have a default value or can accept a value. The default only applies if the option is selected (And FWIW, I am not saying that git is a model of UX ;) )

**Comment by mbrancato** [comment]
regarding @anarcat https://github.com/pallets/click/issues/549#issuecomment-369253406 - The POSIX thing was mostly off the top of my head, just thinking about other drivers / compatibility. But my code was a simple implementation, it needs significant work to resolve ambiguities. I think there are some ways to solve ambiguities by defining an order preference.

Ignoring the space issue causing ambiguities between options and optional arguments, does click support something like the following with three separate results to provide similar functionality as `getopt_long`?

    --bar
    --foo --bar
    --foo=4 --bar

**Comment by sblancov** [comment]
I really need this feature.

I'm developing a CLI and I want to write results to stdout by default and use an option to write a file instead of write to stdout, but I want to specify a path or use a default one when no path is specified. For example:

```
cli -> stdout
cli -f -> default_file
cli -f path -> specific file
```

I have found a workaround:
https://stackoverflow.com/questions/40753999/python-click-make-option-value-optional
But is not as fast as just an annotation.

**Comment by rollnlearn** [comment]
Has click team introduced any way to differential between the default and user-specified values for optional arguments?
