### ISSUE TITLE
Dim not working with styled text + normal text

### ISSUE THREAD

**Issue by Ben-Baert** [pallets/click#575]
If I have styled text (click.style) and a regular string, and then I try to dim by click.secho(..., dim=True), the regular_string bit doesn't get dimmed. 

Example:
![schermafbeelding 2016-05-05 om 13 30 40](https://cloud.githubusercontent.com/assets/419844/15042619/f3595c50-12c5-11e6-860f-c85fafadc2a3.png)

Not sure whether this is a bug or whether I'm simply using it wrong...

**Comment by Atausch** [comment]
By default the styling is self contained, which means that Click does not know what it is wrapping, and so at the end of the wrapped string a reset code is issued. You could use reset=False to use the previous styling, which in your case it would be the red font, but even then "tadaa" would be red and not dim. In order to dim the last text you will need to wrap it in dim.
