### ISSUE TITLE
strange name for program in usage when installing package with command line interfaces using pip

### ISSUE THREAD

**Issue by kotoroshinoto** [pallets/click#589]
on windows at least, the usage will show the script that pip places in the system directory instead of the raw command name. this may be a result of the way that pip works on windows, but I don't know what to do about it.

so the usage will be Usage: gooch_maf_tools-script.py [OPTIONS] COMMAND [ARGS]...
instead of Usage: gooch_maf_tools [OPTIONS] COMMAND [ARGS]...

and I can't tell if there is any way to override the name of the program in usage for click.

**Comment by janhancic** [comment]
Looking at the code, there doesn't seem to be a way to override the name of the program. Would it be possible to add this option somehow? As right now click is reporting the wrong thing as my program name due to how we run our python code, and it would be nice if I could just provide my custom program name.

**Comment by davidism** [comment]
Fixed by #1609, but also you've always been able to pass in `prog_name` when entering a CLI to set the name explicitly.
