### ISSUE TITLE
Don't work KeyboardIterrupt in testing input.

### ISSUE THREAD

**Issue by voronin-opensoft** [pallets/click#596]
Python 2.7
click 6.6

"\x03" doesn't raise interrupt of input.
```python
@click.command()
def input_some():
    click.prompt('some')

runner = CliRunner()
runner.invoke(input_some, input='ENTER\x03')
```
It's endless waiting.

**Comment by untitaker** [comment]
@voronin-opensoft I already told you to ask your question on StackOverflow. That you now rephrase it as a bugreport is not better.

**Comment by voronin-opensoft** [comment]
You are idiot

**Comment by untitaker** [comment]
@voronin-opensoft 

>you are idiot

Okay.

* It is impossible to sanely test a program like this, because the KeyboardInterrupt may be raised anywhere between the previous and next input.
* I recommend that you monkeypatch the internals of your application for this particular test run such that it will raise KeyboardInterrupt itself.
* You expected an API to work in a particular way and opened a bug report when it didn't.
* We could've had this without your insults.
