### ISSUE TITLE
Display manually help

### ISSUE THREAD

**Issue by femtotrader** [pallets/click#618]
Hello,

I'd like my command line do nothing except display cli help if no parameter is passed.
How to force to display help ?

Kind regards

**Comment by Miserlou** [comment]
I'm going CRAZY trying to figure this out right now, this absolutely needs to be a feature, or if it already is, it absolutely needs to be surfaced in the documentation. So annoying.

**Comment by untitaker** [comment]
@femtotrader Use `no_args_is_help=True` on the command parameter. This is enabled for groups by default.

**Comment by untitaker** [comment]
Sorry, actually no_args_is_help is not available for Command, but implemented in #502.

**Comment by Miserlou** [comment]
That isn't a satisfactory solution for us because we have different behavior for noargs with stdin and noargs with stdin.  There are also other scenarios you can obviously imagine where somebody would want to manually display the help text. 

We need this feature surfaced and documented - can you please reopen this ticket?

**Comment by untitaker** [comment]
In that case you can also use `ctx.get_help`, which is internally used as well by `help_option`. It *is* documented, but arguably not very well. Patches are always welcome though!

**Comment by untitaker** [comment]
Also I'd reconsider if printing out the entire help on incorrect usage is obscuring the previously printed error message (which is why click doesn't give the user that much choice in UX design).
