### ISSUE TITLE
Click prompts do not cooperate with readline module

### ISSUE THREAD

**Issue by gumho** [pallets/click#665]
When readline is imported and a user presses backspace during a Click prompt, the entire prompt message is erased and cursor goes to beginning of the line. This can be reproduced with the following code:

```
import click, readline
click.prompt("Input")
```

This is due to [Python issue 12833](https://bugs.python.org/issue12833). The official recommendation is that the prompt should be displayed with raw_input. I noticed that Click first displays the prompt message using echo() and then uses raw_input("") for the prompt. There is also a workaround by passing " " to raw_input, however, that may be ugly in the display.

**Comment by hany** [comment]
Any feedback about this particular issue?

**Comment by famecastle** [comment]
This becomes now a little problematic, since the great 'click-shell` package, which easily extends the `click` package by an interactive shell if no commands or parameters are provided, relies on readline.

What I've done in my (venv'ed) python project to circumvent this problem for now:

- copy the `click` directory from `venv/lib/site-packages/` to the main folder
- run `pip uninstall click`
- edit `click/termui.py` and go to the `f("")` line.
- Replace `f("")` with `f(" ")` (notice the space)
- In the line above, add an `rstrip(" ")` to remove ugly display: `echo(text.rstrip(" "), nl=False, err=err)`

I think the click team should fix this issue since readline is quite a common module included in the Python standard library. How about echoing the prompt as usual, but displaying the prefix in the input-method (like `f(prefix)`) ?
