### ISSUE TITLE
"Missing argument" message uses arg name, not metavar

### ISSUE THREAD

**Issue by andy-maier** [pallets/click#704]
If one defines the metavar different from the argument name, like in:
```
@adapter_group.command('list')
@click.argument('CPC-NAME', type=str, metavar='CPC')
@click.pass_obj
def adapter_list(cmd_obj, cpc_name):
```
the usage line in the help text correctly uses the metavar:
```
Usage: zhmc adapter list [OPTIONS] CPC
```
but the error message when invoked without arguments incorrectly uses the argument name:
```
Error: Missing argument "CPC-NAME".
```

I suggest that the metavar is used consistently in all display to the user.

**Comment by sirosen** [comment]
This is generated by a bit of a head scratcher, in the [formatting code](https://github.com/pallets/click/blob/30fc626263db82e9f339ca8810d207ab089d5575/click/exceptions.py#L117-L145) for a `MissingParameter` error.

If I'm reading this right, it's trying to be generic in its handling of Options and Arguments, so it takes `param.opts` as a relevant "name" for the parameter, and slash delimits all of the available names.
That gets nice help like `Missing option "-f/--foo"`, and explains the issue here.

`Argument.get_usage_pieces` looks at the metavar correctly. Without tracing this out thoroughly, it seems like this is the key difference.

---

Opinion Zone:
The real thing that's wrong here is that `Argument` has a non-empty `opts` value. I've seen this elsewhere in the code and it seems wrong -- the name doesn't help either, as it implies that it's a good detector of Option vs. Argument.
Fixing that would be a breaking change as completion and other advanced usage may depend upon this value.

---

There are a bunch of ways of fixing this.
Probably the least invasive is to make `MissingParameter` formatting read `param.get_usage_pieces` and see if there's anything there. However, there's so much layering going on here, I don't really want to act without some kind of input from the maintainers.
Plus, although pragmatic, that fix is icky and may be abusing the meaning of `get_usage_pieces`.

Something that is common throughout is that a lot of the code handles Options and Argument equivalently. I'm not sure how much people are defining their own param types, and adding an attribute "option-style" vs. "argument-style" would probably resolve a lot of this confusion.

**Comment by sirosen** [comment]
Oh, idea which is not icky or messy and resolves a DRY violation: add a `get_error_hint()` method to Parameters, and fix `MissingParameter` and `BadParameter` to use it.
I'll do that and open a PR now.

**Comment by andy-maier** [comment]
@sirosen Thanks for solving this!!

**Comment by jwilson8767** [comment]
Until this is merged you can do something like: 
`raise click.MissingParameter(param=click.get_current_context().command.params[X])`
Where X is the positional number of the parameter for this command (0 for first possible param, 1 for the next, and so on)
