### ISSUE TITLE
Arguments not picking up environment variables

### ISSUE THREAD

**Issue by garettmd** [pallets/click#714]
I have a setup that looks like this:

```
@click.group()
@click.argument('url', envvar='KANBOARD_URL')
@click.argument('user', envvar='KANBOARD_USER', default='jsonrpc')
@click.argument('token', envvar='KANBOARD_TOKEN')
@pass_connection
def cli(connection, url, user, token):
    do stuff
```

and a subcommand that looks like this:

```
@cli.command()
@click.option('-s', '--search-term', required=True, prompt=True)
@click.option('-n', '--name', required=True, prompt=True)
@click.option('-d', '--description', prompt=True)
@click.option('-p', '--position', prompt=True)
@pass_connection
def add(connection, search_term, name, description, position):
    do stuff
```

Running a command for it, with the necessary environment variables for the `cli` arguments created, would look like this:

```
$ myscript add -s test -n test -d test -p 1
```

Because my environment variables are set, the command should run, but instead I get the help text for the main `cli` function. I've switched the arguments to being options and it picks up the environment variable with no problem. However, in my use case, it makes more sense for these parameters to be arguments, and the arguments should be picking up the env variables anyway

**Comment by IamCathal** [comment]
Looking into this at the moment

**Comment by IamCathal** [comment]
@davidism 

Heres the setup needed to replicate this issue:

`export KANBOARD_URL=kanURL && export KANBOARD_SEARCH_TERM=kanSearchTerm && export KANBOARD_DOMAIN_NAME=kanDomainName`
```python
import click

@click.command()
@click.argument('url',  envvar='KANBOARD_URL')
@click.argument('searchterm',  envvar='KANBOARD_SEARCH_TERM')
@click.argument('domainname',  envvar='KANBOARD_DOMAIN_NAME')
def  cli(url,  searchterm,  domainname):
	print(url, searchterm, domainname) # kanUrl kanSearchTerm kanDomainName
	
if  __name__  ==  '__main__':
	cli()
```

Running this with or without arguments runs fine as expected since all the environment variables are set. However as the issue states the problem arises when options are used after these arguments.

So if we change the script to this which more resembles the original issue:
```python
import click

@click.group()
@click.argument('url',  envvar='KANBOARD_URL')
@click.argument('searchterm',  envvar='KANBOARD_SEARCH_TERM')
@click.argument('domainname',  envvar='KANBOARD_DOMAIN_NAME')
def  cli(url,  searchterm,  domainname):
	print(url, searchterm, domainname)

@cli.command()
@click.option('-s',  '--search-term',  required=True,  prompt=True)
@click.option('-n',  '--name',  required=True,  prompt=True)
def  add(search_term,  name):
	print(search_term, name)


if  __name__  ==  '__main__':
	cli()
```
```
(env) $ python3 test.py kanUrl kanSearch kanDomain add -s testSearch -n testName
kanUrl kanSearch kanDomain
testSearch testName
```
However once on or more arguments aren't added and the options are added, it breaks:
```
(env) $ python3 testTwo.py add -s testSearch -n testName
Usage: testTwo.py [OPTIONS] URL SEARCHTERM DOMAINNAME COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  add
```

From debugging this issue I believe that this is what's happening. Given the input `python test.py kanUrl kanSearch add -s testSearch -n testName` it messes up. It does this as in the function `_process_args_for_args` (or `parse_args`) it parses the first two just fine and assigns kanUrl and kanSearch to their respected args. It then incorrectly tries to assign add to the domain argument i.e if there are 3 arguments defined in the code it tries to assign these first 3 arguments given to those. I believe the flaw is that it iterates over the cli arguments given and consequently mismatches them.

From a high level before parsing the `add` subcommand we would want to see if we have assigned a value to each argument (`url`, `searchterm` and `domain`). If we have reached the `add` argument (or subcommand name or whatever it is officially called) and not all of these arguments have been explicitly given it should then check if the envvar for the remaining ones has been declared and if not then try to execute the default callback.

I hope that explanation was decent.

**Comment by davidism** [comment]
Thanks for the detailed writeup!

The problem is that arguments are positional, not named, so from the parser's perspective "add" appears to be value for the third argument (the domain), rather than the fourth (the command name). For the same reason, once we're out of the parser and into Click's processing, it has no way to know that "add" is not the value of the domain, the fact that it's also the name of a command that could be the fourth arg is not relevant when processing the third arg.

I'm not sure how to solve this, or if it's solvable. There are two rules working against this: parameters are parsed in order, and command line values take precedence over environment values. We can't change the weight of environment variables, otherwise it would be impossible to override an environment value.

**Comment by davidism** [comment]
Based on all this, @IamCathal and I have concluded that it won't be possible to fix this in Click, it's intrinsic to how `Parser.parser_args` and `Parameter.consume_value` work. If you need to pass intermediate arguments as env vars, you'll need to make them options instead, or make the arguments part of the final command.
