### ISSUE TITLE
CliRunner should support parent command options

### ISSUE THREAD

**Issue by warsaw** [pallets/click#831]
In Mailman 3, we have an uber-command `mailman` with lots of subcommands.  `mailman` has a `-C` option and of course subcommands all have their own options.  When I'm testing a subcommand, I import the subcommand and essentially call `CliRunner().invoke(subcmd, (subcmd_options))`.

The problem is that in some cases I need to set options on the parent command, i.e. the `-C` option.  There doesn't appear to be a way to do that, unless of course I've missed it.

I've tried to call `CliRunner().invoke()` on the parent command but had problems that I don't remember the details of.  That generally isn't what I want either, but maybe if that's possible it would be a good workaround.

**Comment by gtristan** [comment]
This seems to work for me.

I'm just doing something like:

```python

# import the main toplevel click group function declared with @click.group()
from mypackage import cli

# Make a fixture like pytest-click does, but not using that thingy
@pytest.fixture(scope="module")
def runner():
    return CliRunner()

# Run a sub command, using the datafiles thing and passing
# a --directory argument to the main command
@pytest.mark.datafiles(DATA_DIR)
def test_sub_command(runner, datafiles):
    projectdir = os.path.join(datafiles.dirname, datafiles.basename)
    result = runner.invoke(cli, [
        '--directory', projectdir,
        'show',
        '--format', '%{name}::%{full-key}',
        'target.bst'
    ])


```

**Comment by fdavis** [comment]
@warsaw is this still an issue? do you have an example I could work on?

**Comment by warsaw** [comment]
I don't know whether this is still a problem.  Nosy @maxking to see if he can give it a look when he gets the chance.

**Comment by davidism** [comment]
I think what you're describing here is wanting to invoke only the subcommand, but needing the processing / values from a parent command in the context because the subcommand relies on them.

There's no way to pass options to a parent when invoking only a subcommand, because commands don't track their parent, they can be arrived at by potentially multiple paths.

However, it is possible to pass in a custom context when invoking. You can set up a context object with the information that the parent command would have stored on it. Assuming the parent uses `ctx.ensure_obj(dict)` to store information in a dict, you can set up that dict manually:

```python
runner.invoke(subcommand, [sub, command, args], obj={"parent": 1, "command": "b", "obj": True})
```
