### ISSUE TITLE
Colors not displaying with mintty (mingw, git bash for windows)

### ISSUE THREAD

**Issue by vhakulinen** [pallets/click#857]
My coworkers running windows with python 3.x and click 6.7 are having hard time with click's colors. Looks like the problem is with the `click.echo` function when printing colors with `click.style`. Note that the colors displays properly with python's own `print` (no matter if colorama is installed or not).

This all is with the terminal that "git bash for windows" ships with. Everything works normally with powershell.

**Comment by segevfiner** [comment]
Since Git for Windows uses `mintty`, which is not a real Windows console, this is to be expected. Any Windows program will think that it's output is redirected since it essentially sees pipes as it's stdio. `click` will detect this and disable colors accordingly:
https://github.com/pallets/click/blob/2e856a5281a29eb4293059b37427643c3d52a19a/click/_compat.py#L574-L579

You can use `winpty`, which is included with GfW, to run your Python scripts. They will than see a real console and should work normally. I think they explain about this in the GfW installer, but not everyone bothers to read all of that and just hit next, next next. (That's also how they often end up with malware).

It might be possible to detect `mintty` and enable colors, but there are also plenty of other IDE terminals, CI environments, and what not. Which can handle colors, but use pipes. So where do you cross the line... There were many attempts to push hacks of this nature into `colorama`, none of them were merged though. `colorama` is kind of abandoned.

**Comment by vhakulinen** [comment]
Thanks for getting back with this. I did some research on this and came in conclusion that the `mintty` is the reason behind this, and instructed others (that use windows) to use other terminal emulator.

If you feel so, you can close this issue.
